; DO NOT EDIT
; GENERATED BY GENPROXY

ifdef RAX
else
.model flat, C
.stack 4096
endif

public glAccum
public __glAccum__
public glAlphaFunc
public __glAlphaFunc__
public glAreTexturesResident
public __glAreTexturesResident__
public glArrayElement
public __glArrayElement__
public glBegin
public __glBegin__
public glBindTexture
public __glBindTexture__
public glBitmap
public __glBitmap__
public glBlendFunc
public __glBlendFunc__
public glCallList
public __glCallList__
public glCallLists
public __glCallLists__
public glClear
public __glClear__
public glClearAccum
public __glClearAccum__
public glClearColor
public __glClearColor__
public glClearDepth
public __glClearDepth__
public glClearIndex
public __glClearIndex__
public glClearStencil
public __glClearStencil__
public glClipPlane
public __glClipPlane__
public glColor3b
public __glColor3b__
public glColor3bv
public __glColor3bv__
public glColor3d
public __glColor3d__
public glColor3dv
public __glColor3dv__
public glColor3f
public __glColor3f__
public glColor3fv
public __glColor3fv__
public glColor3i
public __glColor3i__
public glColor3iv
public __glColor3iv__
public glColor3s
public __glColor3s__
public glColor3sv
public __glColor3sv__
public glColor3ub
public __glColor3ub__
public glColor3ubv
public __glColor3ubv__
public glColor3ui
public __glColor3ui__
public glColor3uiv
public __glColor3uiv__
public glColor3us
public __glColor3us__
public glColor3usv
public __glColor3usv__
public glColor4b
public __glColor4b__
public glColor4bv
public __glColor4bv__
public glColor4d
public __glColor4d__
public glColor4dv
public __glColor4dv__
public glColor4f
public __glColor4f__
public glColor4fv
public __glColor4fv__
public glColor4i
public __glColor4i__
public glColor4iv
public __glColor4iv__
public glColor4s
public __glColor4s__
public glColor4sv
public __glColor4sv__
public glColor4ub
public __glColor4ub__
public glColor4ubv
public __glColor4ubv__
public glColor4ui
public __glColor4ui__
public glColor4uiv
public __glColor4uiv__
public glColor4us
public __glColor4us__
public glColor4usv
public __glColor4usv__
public glColorMask
public __glColorMask__
public glColorMaterial
public __glColorMaterial__
public glColorPointer
public __glColorPointer__
public glCopyPixels
public __glCopyPixels__
public glCopyTexImage1D
public __glCopyTexImage1D__
public glCopyTexImage2D
public __glCopyTexImage2D__
public glCopyTexSubImage1D
public __glCopyTexSubImage1D__
public glCopyTexSubImage2D
public __glCopyTexSubImage2D__
public glCullFace
public __glCullFace__
public glDeleteLists
public __glDeleteLists__
public glDeleteTextures
public __glDeleteTextures__
public glDepthFunc
public __glDepthFunc__
public glDepthMask
public __glDepthMask__
public glDepthRange
public __glDepthRange__
public glDisable
public __glDisable__
public glDisableClientState
public __glDisableClientState__
public glDrawArrays
public __glDrawArrays__
public glDrawBuffer
public __glDrawBuffer__
public glDrawElements
public __glDrawElements__
public glDrawPixels
public __glDrawPixels__
public glEdgeFlag
public __glEdgeFlag__
public glEdgeFlagPointer
public __glEdgeFlagPointer__
public glEdgeFlagv
public __glEdgeFlagv__
public glEnable
public __glEnable__
public glEnableClientState
public __glEnableClientState__
public glEnd
public __glEnd__
public glEndList
public __glEndList__
public glEvalCoord1d
public __glEvalCoord1d__
public glEvalCoord1dv
public __glEvalCoord1dv__
public glEvalCoord1f
public __glEvalCoord1f__
public glEvalCoord1fv
public __glEvalCoord1fv__
public glEvalCoord2d
public __glEvalCoord2d__
public glEvalCoord2dv
public __glEvalCoord2dv__
public glEvalCoord2f
public __glEvalCoord2f__
public glEvalCoord2fv
public __glEvalCoord2fv__
public glEvalMesh1
public __glEvalMesh1__
public glEvalMesh2
public __glEvalMesh2__
public glEvalPoint1
public __glEvalPoint1__
public glEvalPoint2
public __glEvalPoint2__
public glFeedbackBuffer
public __glFeedbackBuffer__
public glFinish
public __glFinish__
public glFlush
public __glFlush__
public glFogf
public __glFogf__
public glFogfv
public __glFogfv__
public glFogi
public __glFogi__
public glFogiv
public __glFogiv__
public glFrontFace
public __glFrontFace__
public glFrustum
public __glFrustum__
public glGenLists
public __glGenLists__
public glGenTextures
public __glGenTextures__
public glGetBooleanv
public __glGetBooleanv__
public glGetClipPlane
public __glGetClipPlane__
public glGetDoublev
public __glGetDoublev__
public glGetError
public __glGetError__
public glGetFloatv
public __glGetFloatv__
public glGetIntegerv
public __glGetIntegerv__
public glGetLightfv
public __glGetLightfv__
public glGetLightiv
public __glGetLightiv__
public glGetMapdv
public __glGetMapdv__
public glGetMapfv
public __glGetMapfv__
public glGetMapiv
public __glGetMapiv__
public glGetMaterialfv
public __glGetMaterialfv__
public glGetMaterialiv
public __glGetMaterialiv__
public glGetPixelMapfv
public __glGetPixelMapfv__
public glGetPixelMapuiv
public __glGetPixelMapuiv__
public glGetPixelMapusv
public __glGetPixelMapusv__
public glGetPointerv
public __glGetPointerv__
public glGetPolygonStipple
public __glGetPolygonStipple__
public glGetString
public __glGetString__
public glGetTexEnvfv
public __glGetTexEnvfv__
public glGetTexEnviv
public __glGetTexEnviv__
public glGetTexGendv
public __glGetTexGendv__
public glGetTexGenfv
public __glGetTexGenfv__
public glGetTexGeniv
public __glGetTexGeniv__
public glGetTexImage
public __glGetTexImage__
public glGetTexLevelParameterfv
public __glGetTexLevelParameterfv__
public glGetTexLevelParameteriv
public __glGetTexLevelParameteriv__
public glGetTexParameterfv
public __glGetTexParameterfv__
public glGetTexParameteriv
public __glGetTexParameteriv__
public glHint
public __glHint__
public glIndexMask
public __glIndexMask__
public glIndexPointer
public __glIndexPointer__
public glIndexd
public __glIndexd__
public glIndexdv
public __glIndexdv__
public glIndexf
public __glIndexf__
public glIndexfv
public __glIndexfv__
public glIndexi
public __glIndexi__
public glIndexiv
public __glIndexiv__
public glIndexs
public __glIndexs__
public glIndexsv
public __glIndexsv__
public glIndexub
public __glIndexub__
public glIndexubv
public __glIndexubv__
public glInitNames
public __glInitNames__
public glInterleavedArrays
public __glInterleavedArrays__
public glIsEnabled
public __glIsEnabled__
public glIsList
public __glIsList__
public glIsTexture
public __glIsTexture__
public glLightModelf
public __glLightModelf__
public glLightModelfv
public __glLightModelfv__
public glLightModeli
public __glLightModeli__
public glLightModeliv
public __glLightModeliv__
public glLightf
public __glLightf__
public glLightfv
public __glLightfv__
public glLighti
public __glLighti__
public glLightiv
public __glLightiv__
public glLineStipple
public __glLineStipple__
public glLineWidth
public __glLineWidth__
public glListBase
public __glListBase__
public glLoadIdentity
public __glLoadIdentity__
public glLoadMatrixd
public __glLoadMatrixd__
public glLoadMatrixf
public __glLoadMatrixf__
public glLoadName
public __glLoadName__
public glLogicOp
public __glLogicOp__
public glMap1d
public __glMap1d__
public glMap1f
public __glMap1f__
public glMap2d
public __glMap2d__
public glMap2f
public __glMap2f__
public glMapGrid1d
public __glMapGrid1d__
public glMapGrid1f
public __glMapGrid1f__
public glMapGrid2d
public __glMapGrid2d__
public glMapGrid2f
public __glMapGrid2f__
public glMaterialf
public __glMaterialf__
public glMaterialfv
public __glMaterialfv__
public glMateriali
public __glMateriali__
public glMaterialiv
public __glMaterialiv__
public glMatrixMode
public __glMatrixMode__
public glMultMatrixd
public __glMultMatrixd__
public glMultMatrixf
public __glMultMatrixf__
public glNewList
public __glNewList__
public glNormal3b
public __glNormal3b__
public glNormal3bv
public __glNormal3bv__
public glNormal3d
public __glNormal3d__
public glNormal3dv
public __glNormal3dv__
public glNormal3f
public __glNormal3f__
public glNormal3fv
public __glNormal3fv__
public glNormal3i
public __glNormal3i__
public glNormal3iv
public __glNormal3iv__
public glNormal3s
public __glNormal3s__
public glNormal3sv
public __glNormal3sv__
public glNormalPointer
public __glNormalPointer__
public glOrtho
public __glOrtho__
public glPassThrough
public __glPassThrough__
public glPixelMapfv
public __glPixelMapfv__
public glPixelMapuiv
public __glPixelMapuiv__
public glPixelMapusv
public __glPixelMapusv__
public glPixelStoref
public __glPixelStoref__
public glPixelStorei
public __glPixelStorei__
public glPixelTransferf
public __glPixelTransferf__
public glPixelTransferi
public __glPixelTransferi__
public glPixelZoom
public __glPixelZoom__
public glPointSize
public __glPointSize__
public glPolygonMode
public __glPolygonMode__
public glPolygonOffset
public __glPolygonOffset__
public glPolygonStipple
public __glPolygonStipple__
public glPopAttrib
public __glPopAttrib__
public glPopClientAttrib
public __glPopClientAttrib__
public glPopMatrix
public __glPopMatrix__
public glPopName
public __glPopName__
public glPrioritizeTextures
public __glPrioritizeTextures__
public glPushAttrib
public __glPushAttrib__
public glPushClientAttrib
public __glPushClientAttrib__
public glPushMatrix
public __glPushMatrix__
public glPushName
public __glPushName__
public glRasterPos2d
public __glRasterPos2d__
public glRasterPos2dv
public __glRasterPos2dv__
public glRasterPos2f
public __glRasterPos2f__
public glRasterPos2fv
public __glRasterPos2fv__
public glRasterPos2i
public __glRasterPos2i__
public glRasterPos2iv
public __glRasterPos2iv__
public glRasterPos2s
public __glRasterPos2s__
public glRasterPos2sv
public __glRasterPos2sv__
public glRasterPos3d
public __glRasterPos3d__
public glRasterPos3dv
public __glRasterPos3dv__
public glRasterPos3f
public __glRasterPos3f__
public glRasterPos3fv
public __glRasterPos3fv__
public glRasterPos3i
public __glRasterPos3i__
public glRasterPos3iv
public __glRasterPos3iv__
public glRasterPos3s
public __glRasterPos3s__
public glRasterPos3sv
public __glRasterPos3sv__
public glRasterPos4d
public __glRasterPos4d__
public glRasterPos4dv
public __glRasterPos4dv__
public glRasterPos4f
public __glRasterPos4f__
public glRasterPos4fv
public __glRasterPos4fv__
public glRasterPos4i
public __glRasterPos4i__
public glRasterPos4iv
public __glRasterPos4iv__
public glRasterPos4s
public __glRasterPos4s__
public glRasterPos4sv
public __glRasterPos4sv__
public glReadBuffer
public __glReadBuffer__
public glReadPixels
public __glReadPixels__
public glRectd
public __glRectd__
public glRectdv
public __glRectdv__
public glRectf
public __glRectf__
public glRectfv
public __glRectfv__
public glRecti
public __glRecti__
public glRectiv
public __glRectiv__
public glRects
public __glRects__
public glRectsv
public __glRectsv__
public glRenderMode
public __glRenderMode__
public glRotated
public __glRotated__
public glRotatef
public __glRotatef__
public glScaled
public __glScaled__
public glScalef
public __glScalef__
public glScissor
public __glScissor__
public glSelectBuffer
public __glSelectBuffer__
public glShadeModel
public __glShadeModel__
public glStencilFunc
public __glStencilFunc__
public glStencilMask
public __glStencilMask__
public glStencilOp
public __glStencilOp__
public glTexCoord1d
public __glTexCoord1d__
public glTexCoord1dv
public __glTexCoord1dv__
public glTexCoord1f
public __glTexCoord1f__
public glTexCoord1fv
public __glTexCoord1fv__
public glTexCoord1i
public __glTexCoord1i__
public glTexCoord1iv
public __glTexCoord1iv__
public glTexCoord1s
public __glTexCoord1s__
public glTexCoord1sv
public __glTexCoord1sv__
public glTexCoord2d
public __glTexCoord2d__
public glTexCoord2dv
public __glTexCoord2dv__
public glTexCoord2f
public __glTexCoord2f__
public glTexCoord2fv
public __glTexCoord2fv__
public glTexCoord2i
public __glTexCoord2i__
public glTexCoord2iv
public __glTexCoord2iv__
public glTexCoord2s
public __glTexCoord2s__
public glTexCoord2sv
public __glTexCoord2sv__
public glTexCoord3d
public __glTexCoord3d__
public glTexCoord3dv
public __glTexCoord3dv__
public glTexCoord3f
public __glTexCoord3f__
public glTexCoord3fv
public __glTexCoord3fv__
public glTexCoord3i
public __glTexCoord3i__
public glTexCoord3iv
public __glTexCoord3iv__
public glTexCoord3s
public __glTexCoord3s__
public glTexCoord3sv
public __glTexCoord3sv__
public glTexCoord4d
public __glTexCoord4d__
public glTexCoord4dv
public __glTexCoord4dv__
public glTexCoord4f
public __glTexCoord4f__
public glTexCoord4fv
public __glTexCoord4fv__
public glTexCoord4i
public __glTexCoord4i__
public glTexCoord4iv
public __glTexCoord4iv__
public glTexCoord4s
public __glTexCoord4s__
public glTexCoord4sv
public __glTexCoord4sv__
public glTexCoordPointer
public __glTexCoordPointer__
public glTexEnvf
public __glTexEnvf__
public glTexEnvfv
public __glTexEnvfv__
public glTexEnvi
public __glTexEnvi__
public glTexEnviv
public __glTexEnviv__
public glTexGend
public __glTexGend__
public glTexGendv
public __glTexGendv__
public glTexGenf
public __glTexGenf__
public glTexGenfv
public __glTexGenfv__
public glTexGeni
public __glTexGeni__
public glTexGeniv
public __glTexGeniv__
public glTexImage1D
public __glTexImage1D__
public glTexImage2D
public __glTexImage2D__
public glTexParameterf
public __glTexParameterf__
public glTexParameterfv
public __glTexParameterfv__
public glTexParameteri
public __glTexParameteri__
public glTexParameteriv
public __glTexParameteriv__
public glTexSubImage1D
public __glTexSubImage1D__
public glTexSubImage2D
public __glTexSubImage2D__
public glTranslated
public __glTranslated__
public glTranslatef
public __glTranslatef__
public glVertex2d
public __glVertex2d__
public glVertex2dv
public __glVertex2dv__
public glVertex2f
public __glVertex2f__
public glVertex2fv
public __glVertex2fv__
public glVertex2i
public __glVertex2i__
public glVertex2iv
public __glVertex2iv__
public glVertex2s
public __glVertex2s__
public glVertex2sv
public __glVertex2sv__
public glVertex3d
public __glVertex3d__
public glVertex3dv
public __glVertex3dv__
public glVertex3f
public __glVertex3f__
public glVertex3fv
public __glVertex3fv__
public glVertex3i
public __glVertex3i__
public glVertex3iv
public __glVertex3iv__
public glVertex3s
public __glVertex3s__
public glVertex3sv
public __glVertex3sv__
public glVertex4d
public __glVertex4d__
public glVertex4dv
public __glVertex4dv__
public glVertex4f
public __glVertex4f__
public glVertex4fv
public __glVertex4fv__
public glVertex4i
public __glVertex4i__
public glVertex4iv
public __glVertex4iv__
public glVertex4s
public __glVertex4s__
public glVertex4sv
public __glVertex4sv__
public glVertexPointer
public __glVertexPointer__
public glViewport
public __glViewport__
public wglChoosePixelFormat
public __wglChoosePixelFormat__
public wglGetLayerPaletteEntries
public __wglGetLayerPaletteEntries__
public wglCopyContext
public __wglCopyContext__
public wglDeleteContext
public __wglDeleteContext__
public wglDescribeLayerPlane
public __wglDescribeLayerPlane__
public wglGetCurrentDC
public __wglGetCurrentDC__
public wglCreateContext
public __wglCreateContext__
public wglCreateLayerContext
public __wglCreateLayerContext__
public wglGetCurrentContext
public __wglGetCurrentContext__
public wglGetDefaultProcAddress
public __wglGetDefaultProcAddress__
public wglUseFontOutlinesW
public __wglUseFontOutlinesW__
public wglDescribePixelFormat
public __wglDescribePixelFormat__
public wglGetPixelFormat
public __wglGetPixelFormat__
public wglGetProcAddress
public __wglGetProcAddress__
public wglMakeCurrent
public __wglMakeCurrent__
public wglRealizeLayerPalette
public __wglRealizeLayerPalette__
public wglSetLayerPaletteEntries
public __wglSetLayerPaletteEntries__
public wglSetPixelFormat
public __wglSetPixelFormat__
public wglShareLists
public __wglShareLists__
public wglSwapBuffers
public __wglSwapBuffers__
public wglSwapLayerBuffers
public __wglSwapLayerBuffers__
public wglSwapMultipleBuffers
public __wglSwapMultipleBuffers__
public wglUseFontBitmapsA
public __wglUseFontBitmapsA__
public wglUseFontBitmapsW
public __wglUseFontBitmapsW__
public wglUseFontOutlinesA
public __wglUseFontOutlinesA__


.data
  __glAccum__ DWORD 0
  __glAlphaFunc__ DWORD 0
  __glAreTexturesResident__ DWORD 0
  __glArrayElement__ DWORD 0
  __glBegin__ DWORD 0
  __glBindTexture__ DWORD 0
  __glBitmap__ DWORD 0
  __glBlendFunc__ DWORD 0
  __glCallList__ DWORD 0
  __glCallLists__ DWORD 0
  __glClear__ DWORD 0
  __glClearAccum__ DWORD 0
  __glClearColor__ DWORD 0
  __glClearDepth__ DWORD 0
  __glClearIndex__ DWORD 0
  __glClearStencil__ DWORD 0
  __glClipPlane__ DWORD 0
  __glColor3b__ DWORD 0
  __glColor3bv__ DWORD 0
  __glColor3d__ DWORD 0
  __glColor3dv__ DWORD 0
  __glColor3f__ DWORD 0
  __glColor3fv__ DWORD 0
  __glColor3i__ DWORD 0
  __glColor3iv__ DWORD 0
  __glColor3s__ DWORD 0
  __glColor3sv__ DWORD 0
  __glColor3ub__ DWORD 0
  __glColor3ubv__ DWORD 0
  __glColor3ui__ DWORD 0
  __glColor3uiv__ DWORD 0
  __glColor3us__ DWORD 0
  __glColor3usv__ DWORD 0
  __glColor4b__ DWORD 0
  __glColor4bv__ DWORD 0
  __glColor4d__ DWORD 0
  __glColor4dv__ DWORD 0
  __glColor4f__ DWORD 0
  __glColor4fv__ DWORD 0
  __glColor4i__ DWORD 0
  __glColor4iv__ DWORD 0
  __glColor4s__ DWORD 0
  __glColor4sv__ DWORD 0
  __glColor4ub__ DWORD 0
  __glColor4ubv__ DWORD 0
  __glColor4ui__ DWORD 0
  __glColor4uiv__ DWORD 0
  __glColor4us__ DWORD 0
  __glColor4usv__ DWORD 0
  __glColorMask__ DWORD 0
  __glColorMaterial__ DWORD 0
  __glColorPointer__ DWORD 0
  __glCopyPixels__ DWORD 0
  __glCopyTexImage1D__ DWORD 0
  __glCopyTexImage2D__ DWORD 0
  __glCopyTexSubImage1D__ DWORD 0
  __glCopyTexSubImage2D__ DWORD 0
  __glCullFace__ DWORD 0
  __glDeleteLists__ DWORD 0
  __glDeleteTextures__ DWORD 0
  __glDepthFunc__ DWORD 0
  __glDepthMask__ DWORD 0
  __glDepthRange__ DWORD 0
  __glDisable__ DWORD 0
  __glDisableClientState__ DWORD 0
  __glDrawArrays__ DWORD 0
  __glDrawBuffer__ DWORD 0
  __glDrawElements__ DWORD 0
  __glDrawPixels__ DWORD 0
  __glEdgeFlag__ DWORD 0
  __glEdgeFlagPointer__ DWORD 0
  __glEdgeFlagv__ DWORD 0
  __glEnable__ DWORD 0
  __glEnableClientState__ DWORD 0
  __glEnd__ DWORD 0
  __glEndList__ DWORD 0
  __glEvalCoord1d__ DWORD 0
  __glEvalCoord1dv__ DWORD 0
  __glEvalCoord1f__ DWORD 0
  __glEvalCoord1fv__ DWORD 0
  __glEvalCoord2d__ DWORD 0
  __glEvalCoord2dv__ DWORD 0
  __glEvalCoord2f__ DWORD 0
  __glEvalCoord2fv__ DWORD 0
  __glEvalMesh1__ DWORD 0
  __glEvalMesh2__ DWORD 0
  __glEvalPoint1__ DWORD 0
  __glEvalPoint2__ DWORD 0
  __glFeedbackBuffer__ DWORD 0
  __glFinish__ DWORD 0
  __glFlush__ DWORD 0
  __glFogf__ DWORD 0
  __glFogfv__ DWORD 0
  __glFogi__ DWORD 0
  __glFogiv__ DWORD 0
  __glFrontFace__ DWORD 0
  __glFrustum__ DWORD 0
  __glGenLists__ DWORD 0
  __glGenTextures__ DWORD 0
  __glGetBooleanv__ DWORD 0
  __glGetClipPlane__ DWORD 0
  __glGetDoublev__ DWORD 0
  __glGetError__ DWORD 0
  __glGetFloatv__ DWORD 0
  __glGetIntegerv__ DWORD 0
  __glGetLightfv__ DWORD 0
  __glGetLightiv__ DWORD 0
  __glGetMapdv__ DWORD 0
  __glGetMapfv__ DWORD 0
  __glGetMapiv__ DWORD 0
  __glGetMaterialfv__ DWORD 0
  __glGetMaterialiv__ DWORD 0
  __glGetPixelMapfv__ DWORD 0
  __glGetPixelMapuiv__ DWORD 0
  __glGetPixelMapusv__ DWORD 0
  __glGetPointerv__ DWORD 0
  __glGetPolygonStipple__ DWORD 0
  __glGetString__ DWORD 0
  __glGetTexEnvfv__ DWORD 0
  __glGetTexEnviv__ DWORD 0
  __glGetTexGendv__ DWORD 0
  __glGetTexGenfv__ DWORD 0
  __glGetTexGeniv__ DWORD 0
  __glGetTexImage__ DWORD 0
  __glGetTexLevelParameterfv__ DWORD 0
  __glGetTexLevelParameteriv__ DWORD 0
  __glGetTexParameterfv__ DWORD 0
  __glGetTexParameteriv__ DWORD 0
  __glHint__ DWORD 0
  __glIndexMask__ DWORD 0
  __glIndexPointer__ DWORD 0
  __glIndexd__ DWORD 0
  __glIndexdv__ DWORD 0
  __glIndexf__ DWORD 0
  __glIndexfv__ DWORD 0
  __glIndexi__ DWORD 0
  __glIndexiv__ DWORD 0
  __glIndexs__ DWORD 0
  __glIndexsv__ DWORD 0
  __glIndexub__ DWORD 0
  __glIndexubv__ DWORD 0
  __glInitNames__ DWORD 0
  __glInterleavedArrays__ DWORD 0
  __glIsEnabled__ DWORD 0
  __glIsList__ DWORD 0
  __glIsTexture__ DWORD 0
  __glLightModelf__ DWORD 0
  __glLightModelfv__ DWORD 0
  __glLightModeli__ DWORD 0
  __glLightModeliv__ DWORD 0
  __glLightf__ DWORD 0
  __glLightfv__ DWORD 0
  __glLighti__ DWORD 0
  __glLightiv__ DWORD 0
  __glLineStipple__ DWORD 0
  __glLineWidth__ DWORD 0
  __glListBase__ DWORD 0
  __glLoadIdentity__ DWORD 0
  __glLoadMatrixd__ DWORD 0
  __glLoadMatrixf__ DWORD 0
  __glLoadName__ DWORD 0
  __glLogicOp__ DWORD 0
  __glMap1d__ DWORD 0
  __glMap1f__ DWORD 0
  __glMap2d__ DWORD 0
  __glMap2f__ DWORD 0
  __glMapGrid1d__ DWORD 0
  __glMapGrid1f__ DWORD 0
  __glMapGrid2d__ DWORD 0
  __glMapGrid2f__ DWORD 0
  __glMaterialf__ DWORD 0
  __glMaterialfv__ DWORD 0
  __glMateriali__ DWORD 0
  __glMaterialiv__ DWORD 0
  __glMatrixMode__ DWORD 0
  __glMultMatrixd__ DWORD 0
  __glMultMatrixf__ DWORD 0
  __glNewList__ DWORD 0
  __glNormal3b__ DWORD 0
  __glNormal3bv__ DWORD 0
  __glNormal3d__ DWORD 0
  __glNormal3dv__ DWORD 0
  __glNormal3f__ DWORD 0
  __glNormal3fv__ DWORD 0
  __glNormal3i__ DWORD 0
  __glNormal3iv__ DWORD 0
  __glNormal3s__ DWORD 0
  __glNormal3sv__ DWORD 0
  __glNormalPointer__ DWORD 0
  __glOrtho__ DWORD 0
  __glPassThrough__ DWORD 0
  __glPixelMapfv__ DWORD 0
  __glPixelMapuiv__ DWORD 0
  __glPixelMapusv__ DWORD 0
  __glPixelStoref__ DWORD 0
  __glPixelStorei__ DWORD 0
  __glPixelTransferf__ DWORD 0
  __glPixelTransferi__ DWORD 0
  __glPixelZoom__ DWORD 0
  __glPointSize__ DWORD 0
  __glPolygonMode__ DWORD 0
  __glPolygonOffset__ DWORD 0
  __glPolygonStipple__ DWORD 0
  __glPopAttrib__ DWORD 0
  __glPopClientAttrib__ DWORD 0
  __glPopMatrix__ DWORD 0
  __glPopName__ DWORD 0
  __glPrioritizeTextures__ DWORD 0
  __glPushAttrib__ DWORD 0
  __glPushClientAttrib__ DWORD 0
  __glPushMatrix__ DWORD 0
  __glPushName__ DWORD 0
  __glRasterPos2d__ DWORD 0
  __glRasterPos2dv__ DWORD 0
  __glRasterPos2f__ DWORD 0
  __glRasterPos2fv__ DWORD 0
  __glRasterPos2i__ DWORD 0
  __glRasterPos2iv__ DWORD 0
  __glRasterPos2s__ DWORD 0
  __glRasterPos2sv__ DWORD 0
  __glRasterPos3d__ DWORD 0
  __glRasterPos3dv__ DWORD 0
  __glRasterPos3f__ DWORD 0
  __glRasterPos3fv__ DWORD 0
  __glRasterPos3i__ DWORD 0
  __glRasterPos3iv__ DWORD 0
  __glRasterPos3s__ DWORD 0
  __glRasterPos3sv__ DWORD 0
  __glRasterPos4d__ DWORD 0
  __glRasterPos4dv__ DWORD 0
  __glRasterPos4f__ DWORD 0
  __glRasterPos4fv__ DWORD 0
  __glRasterPos4i__ DWORD 0
  __glRasterPos4iv__ DWORD 0
  __glRasterPos4s__ DWORD 0
  __glRasterPos4sv__ DWORD 0
  __glReadBuffer__ DWORD 0
  __glReadPixels__ DWORD 0
  __glRectd__ DWORD 0
  __glRectdv__ DWORD 0
  __glRectf__ DWORD 0
  __glRectfv__ DWORD 0
  __glRecti__ DWORD 0
  __glRectiv__ DWORD 0
  __glRects__ DWORD 0
  __glRectsv__ DWORD 0
  __glRenderMode__ DWORD 0
  __glRotated__ DWORD 0
  __glRotatef__ DWORD 0
  __glScaled__ DWORD 0
  __glScalef__ DWORD 0
  __glScissor__ DWORD 0
  __glSelectBuffer__ DWORD 0
  __glShadeModel__ DWORD 0
  __glStencilFunc__ DWORD 0
  __glStencilMask__ DWORD 0
  __glStencilOp__ DWORD 0
  __glTexCoord1d__ DWORD 0
  __glTexCoord1dv__ DWORD 0
  __glTexCoord1f__ DWORD 0
  __glTexCoord1fv__ DWORD 0
  __glTexCoord1i__ DWORD 0
  __glTexCoord1iv__ DWORD 0
  __glTexCoord1s__ DWORD 0
  __glTexCoord1sv__ DWORD 0
  __glTexCoord2d__ DWORD 0
  __glTexCoord2dv__ DWORD 0
  __glTexCoord2f__ DWORD 0
  __glTexCoord2fv__ DWORD 0
  __glTexCoord2i__ DWORD 0
  __glTexCoord2iv__ DWORD 0
  __glTexCoord2s__ DWORD 0
  __glTexCoord2sv__ DWORD 0
  __glTexCoord3d__ DWORD 0
  __glTexCoord3dv__ DWORD 0
  __glTexCoord3f__ DWORD 0
  __glTexCoord3fv__ DWORD 0
  __glTexCoord3i__ DWORD 0
  __glTexCoord3iv__ DWORD 0
  __glTexCoord3s__ DWORD 0
  __glTexCoord3sv__ DWORD 0
  __glTexCoord4d__ DWORD 0
  __glTexCoord4dv__ DWORD 0
  __glTexCoord4f__ DWORD 0
  __glTexCoord4fv__ DWORD 0
  __glTexCoord4i__ DWORD 0
  __glTexCoord4iv__ DWORD 0
  __glTexCoord4s__ DWORD 0
  __glTexCoord4sv__ DWORD 0
  __glTexCoordPointer__ DWORD 0
  __glTexEnvf__ DWORD 0
  __glTexEnvfv__ DWORD 0
  __glTexEnvi__ DWORD 0
  __glTexEnviv__ DWORD 0
  __glTexGend__ DWORD 0
  __glTexGendv__ DWORD 0
  __glTexGenf__ DWORD 0
  __glTexGenfv__ DWORD 0
  __glTexGeni__ DWORD 0
  __glTexGeniv__ DWORD 0
  __glTexImage1D__ DWORD 0
  __glTexImage2D__ DWORD 0
  __glTexParameterf__ DWORD 0
  __glTexParameterfv__ DWORD 0
  __glTexParameteri__ DWORD 0
  __glTexParameteriv__ DWORD 0
  __glTexSubImage1D__ DWORD 0
  __glTexSubImage2D__ DWORD 0
  __glTranslated__ DWORD 0
  __glTranslatef__ DWORD 0
  __glVertex2d__ DWORD 0
  __glVertex2dv__ DWORD 0
  __glVertex2f__ DWORD 0
  __glVertex2fv__ DWORD 0
  __glVertex2i__ DWORD 0
  __glVertex2iv__ DWORD 0
  __glVertex2s__ DWORD 0
  __glVertex2sv__ DWORD 0
  __glVertex3d__ DWORD 0
  __glVertex3dv__ DWORD 0
  __glVertex3f__ DWORD 0
  __glVertex3fv__ DWORD 0
  __glVertex3i__ DWORD 0
  __glVertex3iv__ DWORD 0
  __glVertex3s__ DWORD 0
  __glVertex3sv__ DWORD 0
  __glVertex4d__ DWORD 0
  __glVertex4dv__ DWORD 0
  __glVertex4f__ DWORD 0
  __glVertex4fv__ DWORD 0
  __glVertex4i__ DWORD 0
  __glVertex4iv__ DWORD 0
  __glVertex4s__ DWORD 0
  __glVertex4sv__ DWORD 0
  __glVertexPointer__ DWORD 0
  __glViewport__ DWORD 0
  __wglChoosePixelFormat__ DWORD 0
  __wglGetLayerPaletteEntries__ DWORD 0
  __wglCopyContext__ DWORD 0
  __wglDeleteContext__ DWORD 0
  __wglDescribeLayerPlane__ DWORD 0
  __wglGetCurrentDC__ DWORD 0
  __wglCreateContext__ DWORD 0
  __wglCreateLayerContext__ DWORD 0
  __wglGetCurrentContext__ DWORD 0
  __wglGetDefaultProcAddress__ DWORD 0
  __wglUseFontOutlinesW__ DWORD 0
  __wglDescribePixelFormat__ DWORD 0
  __wglGetPixelFormat__ DWORD 0
  __wglGetProcAddress__ DWORD 0
  __wglMakeCurrent__ DWORD 0
  __wglRealizeLayerPalette__ DWORD 0
  __wglSetLayerPaletteEntries__ DWORD 0
  __wglSetPixelFormat__ DWORD 0
  __wglShareLists__ DWORD 0
  __wglSwapBuffers__ DWORD 0
  __wglSwapLayerBuffers__ DWORD 0
  __wglSwapMultipleBuffers__ DWORD 0
  __wglUseFontBitmapsA__ DWORD 0
  __wglUseFontBitmapsW__ DWORD 0
  __wglUseFontOutlinesA__ DWORD 0


.code
glAccum:
  jmp DWORD ptr __glAccum__
glAlphaFunc:
  jmp DWORD ptr __glAlphaFunc__
glAreTexturesResident:
  jmp DWORD ptr __glAreTexturesResident__
glArrayElement:
  jmp DWORD ptr __glArrayElement__
glBegin:
  jmp DWORD ptr __glBegin__
glBindTexture:
  jmp DWORD ptr __glBindTexture__
glBitmap:
  jmp DWORD ptr __glBitmap__
glBlendFunc:
  jmp DWORD ptr __glBlendFunc__
glCallList:
  jmp DWORD ptr __glCallList__
glCallLists:
  jmp DWORD ptr __glCallLists__
glClear:
  jmp DWORD ptr __glClear__
glClearAccum:
  jmp DWORD ptr __glClearAccum__
glClearColor:
  jmp DWORD ptr __glClearColor__
glClearDepth:
  jmp DWORD ptr __glClearDepth__
glClearIndex:
  jmp DWORD ptr __glClearIndex__
glClearStencil:
  jmp DWORD ptr __glClearStencil__
glClipPlane:
  jmp DWORD ptr __glClipPlane__
glColor3b:
  jmp DWORD ptr __glColor3b__
glColor3bv:
  jmp DWORD ptr __glColor3bv__
glColor3d:
  jmp DWORD ptr __glColor3d__
glColor3dv:
  jmp DWORD ptr __glColor3dv__
glColor3f:
  jmp DWORD ptr __glColor3f__
glColor3fv:
  jmp DWORD ptr __glColor3fv__
glColor3i:
  jmp DWORD ptr __glColor3i__
glColor3iv:
  jmp DWORD ptr __glColor3iv__
glColor3s:
  jmp DWORD ptr __glColor3s__
glColor3sv:
  jmp DWORD ptr __glColor3sv__
glColor3ub:
  jmp DWORD ptr __glColor3ub__
glColor3ubv:
  jmp DWORD ptr __glColor3ubv__
glColor3ui:
  jmp DWORD ptr __glColor3ui__
glColor3uiv:
  jmp DWORD ptr __glColor3uiv__
glColor3us:
  jmp DWORD ptr __glColor3us__
glColor3usv:
  jmp DWORD ptr __glColor3usv__
glColor4b:
  jmp DWORD ptr __glColor4b__
glColor4bv:
  jmp DWORD ptr __glColor4bv__
glColor4d:
  jmp DWORD ptr __glColor4d__
glColor4dv:
  jmp DWORD ptr __glColor4dv__
glColor4f:
  jmp DWORD ptr __glColor4f__
glColor4fv:
  jmp DWORD ptr __glColor4fv__
glColor4i:
  jmp DWORD ptr __glColor4i__
glColor4iv:
  jmp DWORD ptr __glColor4iv__
glColor4s:
  jmp DWORD ptr __glColor4s__
glColor4sv:
  jmp DWORD ptr __glColor4sv__
glColor4ub:
  jmp DWORD ptr __glColor4ub__
glColor4ubv:
  jmp DWORD ptr __glColor4ubv__
glColor4ui:
  jmp DWORD ptr __glColor4ui__
glColor4uiv:
  jmp DWORD ptr __glColor4uiv__
glColor4us:
  jmp DWORD ptr __glColor4us__
glColor4usv:
  jmp DWORD ptr __glColor4usv__
glColorMask:
  jmp DWORD ptr __glColorMask__
glColorMaterial:
  jmp DWORD ptr __glColorMaterial__
glColorPointer:
  jmp DWORD ptr __glColorPointer__
glCopyPixels:
  jmp DWORD ptr __glCopyPixels__
glCopyTexImage1D:
  jmp DWORD ptr __glCopyTexImage1D__
glCopyTexImage2D:
  jmp DWORD ptr __glCopyTexImage2D__
glCopyTexSubImage1D:
  jmp DWORD ptr __glCopyTexSubImage1D__
glCopyTexSubImage2D:
  jmp DWORD ptr __glCopyTexSubImage2D__
glCullFace:
  jmp DWORD ptr __glCullFace__
glDeleteLists:
  jmp DWORD ptr __glDeleteLists__
glDeleteTextures:
  jmp DWORD ptr __glDeleteTextures__
glDepthFunc:
  jmp DWORD ptr __glDepthFunc__
glDepthMask:
  jmp DWORD ptr __glDepthMask__
glDepthRange:
  jmp DWORD ptr __glDepthRange__
glDisable:
  jmp DWORD ptr __glDisable__
glDisableClientState:
  jmp DWORD ptr __glDisableClientState__
glDrawArrays:
  jmp DWORD ptr __glDrawArrays__
glDrawBuffer:
  jmp DWORD ptr __glDrawBuffer__
glDrawElements:
  jmp DWORD ptr __glDrawElements__
glDrawPixels:
  jmp DWORD ptr __glDrawPixels__
glEdgeFlag:
  jmp DWORD ptr __glEdgeFlag__
glEdgeFlagPointer:
  jmp DWORD ptr __glEdgeFlagPointer__
glEdgeFlagv:
  jmp DWORD ptr __glEdgeFlagv__
glEnable:
  jmp DWORD ptr __glEnable__
glEnableClientState:
  jmp DWORD ptr __glEnableClientState__
glEnd:
  jmp DWORD ptr __glEnd__
glEndList:
  jmp DWORD ptr __glEndList__
glEvalCoord1d:
  jmp DWORD ptr __glEvalCoord1d__
glEvalCoord1dv:
  jmp DWORD ptr __glEvalCoord1dv__
glEvalCoord1f:
  jmp DWORD ptr __glEvalCoord1f__
glEvalCoord1fv:
  jmp DWORD ptr __glEvalCoord1fv__
glEvalCoord2d:
  jmp DWORD ptr __glEvalCoord2d__
glEvalCoord2dv:
  jmp DWORD ptr __glEvalCoord2dv__
glEvalCoord2f:
  jmp DWORD ptr __glEvalCoord2f__
glEvalCoord2fv:
  jmp DWORD ptr __glEvalCoord2fv__
glEvalMesh1:
  jmp DWORD ptr __glEvalMesh1__
glEvalMesh2:
  jmp DWORD ptr __glEvalMesh2__
glEvalPoint1:
  jmp DWORD ptr __glEvalPoint1__
glEvalPoint2:
  jmp DWORD ptr __glEvalPoint2__
glFeedbackBuffer:
  jmp DWORD ptr __glFeedbackBuffer__
glFinish:
  jmp DWORD ptr __glFinish__
glFlush:
  jmp DWORD ptr __glFlush__
glFogf:
  jmp DWORD ptr __glFogf__
glFogfv:
  jmp DWORD ptr __glFogfv__
glFogi:
  jmp DWORD ptr __glFogi__
glFogiv:
  jmp DWORD ptr __glFogiv__
glFrontFace:
  jmp DWORD ptr __glFrontFace__
glFrustum:
  jmp DWORD ptr __glFrustum__
glGenLists:
  jmp DWORD ptr __glGenLists__
glGenTextures:
  jmp DWORD ptr __glGenTextures__
glGetBooleanv:
  jmp DWORD ptr __glGetBooleanv__
glGetClipPlane:
  jmp DWORD ptr __glGetClipPlane__
glGetDoublev:
  jmp DWORD ptr __glGetDoublev__
glGetError:
  jmp DWORD ptr __glGetError__
glGetFloatv:
  jmp DWORD ptr __glGetFloatv__
glGetIntegerv:
  jmp DWORD ptr __glGetIntegerv__
glGetLightfv:
  jmp DWORD ptr __glGetLightfv__
glGetLightiv:
  jmp DWORD ptr __glGetLightiv__
glGetMapdv:
  jmp DWORD ptr __glGetMapdv__
glGetMapfv:
  jmp DWORD ptr __glGetMapfv__
glGetMapiv:
  jmp DWORD ptr __glGetMapiv__
glGetMaterialfv:
  jmp DWORD ptr __glGetMaterialfv__
glGetMaterialiv:
  jmp DWORD ptr __glGetMaterialiv__
glGetPixelMapfv:
  jmp DWORD ptr __glGetPixelMapfv__
glGetPixelMapuiv:
  jmp DWORD ptr __glGetPixelMapuiv__
glGetPixelMapusv:
  jmp DWORD ptr __glGetPixelMapusv__
glGetPointerv:
  jmp DWORD ptr __glGetPointerv__
glGetPolygonStipple:
  jmp DWORD ptr __glGetPolygonStipple__
glGetString:
  jmp DWORD ptr __glGetString__
glGetTexEnvfv:
  jmp DWORD ptr __glGetTexEnvfv__
glGetTexEnviv:
  jmp DWORD ptr __glGetTexEnviv__
glGetTexGendv:
  jmp DWORD ptr __glGetTexGendv__
glGetTexGenfv:
  jmp DWORD ptr __glGetTexGenfv__
glGetTexGeniv:
  jmp DWORD ptr __glGetTexGeniv__
glGetTexImage:
  jmp DWORD ptr __glGetTexImage__
glGetTexLevelParameterfv:
  jmp DWORD ptr __glGetTexLevelParameterfv__
glGetTexLevelParameteriv:
  jmp DWORD ptr __glGetTexLevelParameteriv__
glGetTexParameterfv:
  jmp DWORD ptr __glGetTexParameterfv__
glGetTexParameteriv:
  jmp DWORD ptr __glGetTexParameteriv__
glHint:
  jmp DWORD ptr __glHint__
glIndexMask:
  jmp DWORD ptr __glIndexMask__
glIndexPointer:
  jmp DWORD ptr __glIndexPointer__
glIndexd:
  jmp DWORD ptr __glIndexd__
glIndexdv:
  jmp DWORD ptr __glIndexdv__
glIndexf:
  jmp DWORD ptr __glIndexf__
glIndexfv:
  jmp DWORD ptr __glIndexfv__
glIndexi:
  jmp DWORD ptr __glIndexi__
glIndexiv:
  jmp DWORD ptr __glIndexiv__
glIndexs:
  jmp DWORD ptr __glIndexs__
glIndexsv:
  jmp DWORD ptr __glIndexsv__
glIndexub:
  jmp DWORD ptr __glIndexub__
glIndexubv:
  jmp DWORD ptr __glIndexubv__
glInitNames:
  jmp DWORD ptr __glInitNames__
glInterleavedArrays:
  jmp DWORD ptr __glInterleavedArrays__
glIsEnabled:
  jmp DWORD ptr __glIsEnabled__
glIsList:
  jmp DWORD ptr __glIsList__
glIsTexture:
  jmp DWORD ptr __glIsTexture__
glLightModelf:
  jmp DWORD ptr __glLightModelf__
glLightModelfv:
  jmp DWORD ptr __glLightModelfv__
glLightModeli:
  jmp DWORD ptr __glLightModeli__
glLightModeliv:
  jmp DWORD ptr __glLightModeliv__
glLightf:
  jmp DWORD ptr __glLightf__
glLightfv:
  jmp DWORD ptr __glLightfv__
glLighti:
  jmp DWORD ptr __glLighti__
glLightiv:
  jmp DWORD ptr __glLightiv__
glLineStipple:
  jmp DWORD ptr __glLineStipple__
glLineWidth:
  jmp DWORD ptr __glLineWidth__
glListBase:
  jmp DWORD ptr __glListBase__
glLoadIdentity:
  jmp DWORD ptr __glLoadIdentity__
glLoadMatrixd:
  jmp DWORD ptr __glLoadMatrixd__
glLoadMatrixf:
  jmp DWORD ptr __glLoadMatrixf__
glLoadName:
  jmp DWORD ptr __glLoadName__
glLogicOp:
  jmp DWORD ptr __glLogicOp__
glMap1d:
  jmp DWORD ptr __glMap1d__
glMap1f:
  jmp DWORD ptr __glMap1f__
glMap2d:
  jmp DWORD ptr __glMap2d__
glMap2f:
  jmp DWORD ptr __glMap2f__
glMapGrid1d:
  jmp DWORD ptr __glMapGrid1d__
glMapGrid1f:
  jmp DWORD ptr __glMapGrid1f__
glMapGrid2d:
  jmp DWORD ptr __glMapGrid2d__
glMapGrid2f:
  jmp DWORD ptr __glMapGrid2f__
glMaterialf:
  jmp DWORD ptr __glMaterialf__
glMaterialfv:
  jmp DWORD ptr __glMaterialfv__
glMateriali:
  jmp DWORD ptr __glMateriali__
glMaterialiv:
  jmp DWORD ptr __glMaterialiv__
glMatrixMode:
  jmp DWORD ptr __glMatrixMode__
glMultMatrixd:
  jmp DWORD ptr __glMultMatrixd__
glMultMatrixf:
  jmp DWORD ptr __glMultMatrixf__
glNewList:
  jmp DWORD ptr __glNewList__
glNormal3b:
  jmp DWORD ptr __glNormal3b__
glNormal3bv:
  jmp DWORD ptr __glNormal3bv__
glNormal3d:
  jmp DWORD ptr __glNormal3d__
glNormal3dv:
  jmp DWORD ptr __glNormal3dv__
glNormal3f:
  jmp DWORD ptr __glNormal3f__
glNormal3fv:
  jmp DWORD ptr __glNormal3fv__
glNormal3i:
  jmp DWORD ptr __glNormal3i__
glNormal3iv:
  jmp DWORD ptr __glNormal3iv__
glNormal3s:
  jmp DWORD ptr __glNormal3s__
glNormal3sv:
  jmp DWORD ptr __glNormal3sv__
glNormalPointer:
  jmp DWORD ptr __glNormalPointer__
glOrtho:
  jmp DWORD ptr __glOrtho__
glPassThrough:
  jmp DWORD ptr __glPassThrough__
glPixelMapfv:
  jmp DWORD ptr __glPixelMapfv__
glPixelMapuiv:
  jmp DWORD ptr __glPixelMapuiv__
glPixelMapusv:
  jmp DWORD ptr __glPixelMapusv__
glPixelStoref:
  jmp DWORD ptr __glPixelStoref__
glPixelStorei:
  jmp DWORD ptr __glPixelStorei__
glPixelTransferf:
  jmp DWORD ptr __glPixelTransferf__
glPixelTransferi:
  jmp DWORD ptr __glPixelTransferi__
glPixelZoom:
  jmp DWORD ptr __glPixelZoom__
glPointSize:
  jmp DWORD ptr __glPointSize__
glPolygonMode:
  jmp DWORD ptr __glPolygonMode__
glPolygonOffset:
  jmp DWORD ptr __glPolygonOffset__
glPolygonStipple:
  jmp DWORD ptr __glPolygonStipple__
glPopAttrib:
  jmp DWORD ptr __glPopAttrib__
glPopClientAttrib:
  jmp DWORD ptr __glPopClientAttrib__
glPopMatrix:
  jmp DWORD ptr __glPopMatrix__
glPopName:
  jmp DWORD ptr __glPopName__
glPrioritizeTextures:
  jmp DWORD ptr __glPrioritizeTextures__
glPushAttrib:
  jmp DWORD ptr __glPushAttrib__
glPushClientAttrib:
  jmp DWORD ptr __glPushClientAttrib__
glPushMatrix:
  jmp DWORD ptr __glPushMatrix__
glPushName:
  jmp DWORD ptr __glPushName__
glRasterPos2d:
  jmp DWORD ptr __glRasterPos2d__
glRasterPos2dv:
  jmp DWORD ptr __glRasterPos2dv__
glRasterPos2f:
  jmp DWORD ptr __glRasterPos2f__
glRasterPos2fv:
  jmp DWORD ptr __glRasterPos2fv__
glRasterPos2i:
  jmp DWORD ptr __glRasterPos2i__
glRasterPos2iv:
  jmp DWORD ptr __glRasterPos2iv__
glRasterPos2s:
  jmp DWORD ptr __glRasterPos2s__
glRasterPos2sv:
  jmp DWORD ptr __glRasterPos2sv__
glRasterPos3d:
  jmp DWORD ptr __glRasterPos3d__
glRasterPos3dv:
  jmp DWORD ptr __glRasterPos3dv__
glRasterPos3f:
  jmp DWORD ptr __glRasterPos3f__
glRasterPos3fv:
  jmp DWORD ptr __glRasterPos3fv__
glRasterPos3i:
  jmp DWORD ptr __glRasterPos3i__
glRasterPos3iv:
  jmp DWORD ptr __glRasterPos3iv__
glRasterPos3s:
  jmp DWORD ptr __glRasterPos3s__
glRasterPos3sv:
  jmp DWORD ptr __glRasterPos3sv__
glRasterPos4d:
  jmp DWORD ptr __glRasterPos4d__
glRasterPos4dv:
  jmp DWORD ptr __glRasterPos4dv__
glRasterPos4f:
  jmp DWORD ptr __glRasterPos4f__
glRasterPos4fv:
  jmp DWORD ptr __glRasterPos4fv__
glRasterPos4i:
  jmp DWORD ptr __glRasterPos4i__
glRasterPos4iv:
  jmp DWORD ptr __glRasterPos4iv__
glRasterPos4s:
  jmp DWORD ptr __glRasterPos4s__
glRasterPos4sv:
  jmp DWORD ptr __glRasterPos4sv__
glReadBuffer:
  jmp DWORD ptr __glReadBuffer__
glReadPixels:
  jmp DWORD ptr __glReadPixels__
glRectd:
  jmp DWORD ptr __glRectd__
glRectdv:
  jmp DWORD ptr __glRectdv__
glRectf:
  jmp DWORD ptr __glRectf__
glRectfv:
  jmp DWORD ptr __glRectfv__
glRecti:
  jmp DWORD ptr __glRecti__
glRectiv:
  jmp DWORD ptr __glRectiv__
glRects:
  jmp DWORD ptr __glRects__
glRectsv:
  jmp DWORD ptr __glRectsv__
glRenderMode:
  jmp DWORD ptr __glRenderMode__
glRotated:
  jmp DWORD ptr __glRotated__
glRotatef:
  jmp DWORD ptr __glRotatef__
glScaled:
  jmp DWORD ptr __glScaled__
glScalef:
  jmp DWORD ptr __glScalef__
glScissor:
  jmp DWORD ptr __glScissor__
glSelectBuffer:
  jmp DWORD ptr __glSelectBuffer__
glShadeModel:
  jmp DWORD ptr __glShadeModel__
glStencilFunc:
  jmp DWORD ptr __glStencilFunc__
glStencilMask:
  jmp DWORD ptr __glStencilMask__
glStencilOp:
  jmp DWORD ptr __glStencilOp__
glTexCoord1d:
  jmp DWORD ptr __glTexCoord1d__
glTexCoord1dv:
  jmp DWORD ptr __glTexCoord1dv__
glTexCoord1f:
  jmp DWORD ptr __glTexCoord1f__
glTexCoord1fv:
  jmp DWORD ptr __glTexCoord1fv__
glTexCoord1i:
  jmp DWORD ptr __glTexCoord1i__
glTexCoord1iv:
  jmp DWORD ptr __glTexCoord1iv__
glTexCoord1s:
  jmp DWORD ptr __glTexCoord1s__
glTexCoord1sv:
  jmp DWORD ptr __glTexCoord1sv__
glTexCoord2d:
  jmp DWORD ptr __glTexCoord2d__
glTexCoord2dv:
  jmp DWORD ptr __glTexCoord2dv__
glTexCoord2f:
  jmp DWORD ptr __glTexCoord2f__
glTexCoord2fv:
  jmp DWORD ptr __glTexCoord2fv__
glTexCoord2i:
  jmp DWORD ptr __glTexCoord2i__
glTexCoord2iv:
  jmp DWORD ptr __glTexCoord2iv__
glTexCoord2s:
  jmp DWORD ptr __glTexCoord2s__
glTexCoord2sv:
  jmp DWORD ptr __glTexCoord2sv__
glTexCoord3d:
  jmp DWORD ptr __glTexCoord3d__
glTexCoord3dv:
  jmp DWORD ptr __glTexCoord3dv__
glTexCoord3f:
  jmp DWORD ptr __glTexCoord3f__
glTexCoord3fv:
  jmp DWORD ptr __glTexCoord3fv__
glTexCoord3i:
  jmp DWORD ptr __glTexCoord3i__
glTexCoord3iv:
  jmp DWORD ptr __glTexCoord3iv__
glTexCoord3s:
  jmp DWORD ptr __glTexCoord3s__
glTexCoord3sv:
  jmp DWORD ptr __glTexCoord3sv__
glTexCoord4d:
  jmp DWORD ptr __glTexCoord4d__
glTexCoord4dv:
  jmp DWORD ptr __glTexCoord4dv__
glTexCoord4f:
  jmp DWORD ptr __glTexCoord4f__
glTexCoord4fv:
  jmp DWORD ptr __glTexCoord4fv__
glTexCoord4i:
  jmp DWORD ptr __glTexCoord4i__
glTexCoord4iv:
  jmp DWORD ptr __glTexCoord4iv__
glTexCoord4s:
  jmp DWORD ptr __glTexCoord4s__
glTexCoord4sv:
  jmp DWORD ptr __glTexCoord4sv__
glTexCoordPointer:
  jmp DWORD ptr __glTexCoordPointer__
glTexEnvf:
  jmp DWORD ptr __glTexEnvf__
glTexEnvfv:
  jmp DWORD ptr __glTexEnvfv__
glTexEnvi:
  jmp DWORD ptr __glTexEnvi__
glTexEnviv:
  jmp DWORD ptr __glTexEnviv__
glTexGend:
  jmp DWORD ptr __glTexGend__
glTexGendv:
  jmp DWORD ptr __glTexGendv__
glTexGenf:
  jmp DWORD ptr __glTexGenf__
glTexGenfv:
  jmp DWORD ptr __glTexGenfv__
glTexGeni:
  jmp DWORD ptr __glTexGeni__
glTexGeniv:
  jmp DWORD ptr __glTexGeniv__
glTexImage1D:
  jmp DWORD ptr __glTexImage1D__
glTexImage2D:
  jmp DWORD ptr __glTexImage2D__
glTexParameterf:
  jmp DWORD ptr __glTexParameterf__
glTexParameterfv:
  jmp DWORD ptr __glTexParameterfv__
glTexParameteri:
  jmp DWORD ptr __glTexParameteri__
glTexParameteriv:
  jmp DWORD ptr __glTexParameteriv__
glTexSubImage1D:
  jmp DWORD ptr __glTexSubImage1D__
glTexSubImage2D:
  jmp DWORD ptr __glTexSubImage2D__
glTranslated:
  jmp DWORD ptr __glTranslated__
glTranslatef:
  jmp DWORD ptr __glTranslatef__
glVertex2d:
  jmp DWORD ptr __glVertex2d__
glVertex2dv:
  jmp DWORD ptr __glVertex2dv__
glVertex2f:
  jmp DWORD ptr __glVertex2f__
glVertex2fv:
  jmp DWORD ptr __glVertex2fv__
glVertex2i:
  jmp DWORD ptr __glVertex2i__
glVertex2iv:
  jmp DWORD ptr __glVertex2iv__
glVertex2s:
  jmp DWORD ptr __glVertex2s__
glVertex2sv:
  jmp DWORD ptr __glVertex2sv__
glVertex3d:
  jmp DWORD ptr __glVertex3d__
glVertex3dv:
  jmp DWORD ptr __glVertex3dv__
glVertex3f:
  jmp DWORD ptr __glVertex3f__
glVertex3fv:
  jmp DWORD ptr __glVertex3fv__
glVertex3i:
  jmp DWORD ptr __glVertex3i__
glVertex3iv:
  jmp DWORD ptr __glVertex3iv__
glVertex3s:
  jmp DWORD ptr __glVertex3s__
glVertex3sv:
  jmp DWORD ptr __glVertex3sv__
glVertex4d:
  jmp DWORD ptr __glVertex4d__
glVertex4dv:
  jmp DWORD ptr __glVertex4dv__
glVertex4f:
  jmp DWORD ptr __glVertex4f__
glVertex4fv:
  jmp DWORD ptr __glVertex4fv__
glVertex4i:
  jmp DWORD ptr __glVertex4i__
glVertex4iv:
  jmp DWORD ptr __glVertex4iv__
glVertex4s:
  jmp DWORD ptr __glVertex4s__
glVertex4sv:
  jmp DWORD ptr __glVertex4sv__
glVertexPointer:
  jmp DWORD ptr __glVertexPointer__
glViewport:
  jmp DWORD ptr __glViewport__
wglChoosePixelFormat:
  jmp DWORD ptr __wglChoosePixelFormat__
wglGetLayerPaletteEntries:
  jmp DWORD ptr __wglGetLayerPaletteEntries__
wglCopyContext:
  jmp DWORD ptr __wglCopyContext__
wglDeleteContext:
  jmp DWORD ptr __wglDeleteContext__
wglDescribeLayerPlane:
  jmp DWORD ptr __wglDescribeLayerPlane__
wglGetCurrentDC:
  jmp DWORD ptr __wglGetCurrentDC__
wglCreateContext:
  jmp DWORD ptr __wglCreateContext__
wglCreateLayerContext:
  jmp DWORD ptr __wglCreateLayerContext__
wglGetCurrentContext:
  jmp DWORD ptr __wglGetCurrentContext__
wglGetDefaultProcAddress:
  jmp DWORD ptr __wglGetDefaultProcAddress__
wglUseFontOutlinesW:
  jmp DWORD ptr __wglUseFontOutlinesW__
wglDescribePixelFormat:
  jmp DWORD ptr __wglDescribePixelFormat__
wglGetPixelFormat:
  jmp DWORD ptr __wglGetPixelFormat__
wglGetProcAddress:
  jmp DWORD ptr __wglGetProcAddress__
wglMakeCurrent:
  jmp DWORD ptr __wglMakeCurrent__
wglRealizeLayerPalette:
  jmp DWORD ptr __wglRealizeLayerPalette__
wglSetLayerPaletteEntries:
  jmp DWORD ptr __wglSetLayerPaletteEntries__
wglSetPixelFormat:
  jmp DWORD ptr __wglSetPixelFormat__
wglShareLists:
  jmp DWORD ptr __wglShareLists__
wglSwapBuffers:
  jmp DWORD ptr __wglSwapBuffers__
wglSwapLayerBuffers:
  jmp DWORD ptr __wglSwapLayerBuffers__
wglSwapMultipleBuffers:
  jmp DWORD ptr __wglSwapMultipleBuffers__
wglUseFontBitmapsA:
  jmp DWORD ptr __wglUseFontBitmapsA__
wglUseFontBitmapsW:
  jmp DWORD ptr __wglUseFontBitmapsW__
wglUseFontOutlinesA:
  jmp DWORD ptr __wglUseFontOutlinesA__


end

