/* ==================================
 * COMPUTER GENERATED -- DO NOT EDIT
 * ==================================
 */

#include <windows.h>

extern FARPROC __glAccum__;
extern FARPROC __glAlphaFunc__;
extern FARPROC __glAreTexturesResident__;
extern FARPROC __glArrayElement__;
extern FARPROC __glBegin__;
extern FARPROC __glBindTexture__;
extern FARPROC __glBitmap__;
extern FARPROC __glBlendFunc__;
extern FARPROC __glCallList__;
extern FARPROC __glCallLists__;
extern FARPROC __glClear__;
extern FARPROC __glClearAccum__;
extern FARPROC __glClearColor__;
extern FARPROC __glClearDepth__;
extern FARPROC __glClearIndex__;
extern FARPROC __glClearStencil__;
extern FARPROC __glClipPlane__;
extern FARPROC __glColor3b__;
extern FARPROC __glColor3bv__;
extern FARPROC __glColor3d__;
extern FARPROC __glColor3dv__;
extern FARPROC __glColor3f__;
extern FARPROC __glColor3fv__;
extern FARPROC __glColor3i__;
extern FARPROC __glColor3iv__;
extern FARPROC __glColor3s__;
extern FARPROC __glColor3sv__;
extern FARPROC __glColor3ub__;
extern FARPROC __glColor3ubv__;
extern FARPROC __glColor3ui__;
extern FARPROC __glColor3uiv__;
extern FARPROC __glColor3us__;
extern FARPROC __glColor3usv__;
extern FARPROC __glColor4b__;
extern FARPROC __glColor4bv__;
extern FARPROC __glColor4d__;
extern FARPROC __glColor4dv__;
extern FARPROC __glColor4f__;
extern FARPROC __glColor4fv__;
extern FARPROC __glColor4i__;
extern FARPROC __glColor4iv__;
extern FARPROC __glColor4s__;
extern FARPROC __glColor4sv__;
extern FARPROC __glColor4ub__;
extern FARPROC __glColor4ubv__;
extern FARPROC __glColor4ui__;
extern FARPROC __glColor4uiv__;
extern FARPROC __glColor4us__;
extern FARPROC __glColor4usv__;
extern FARPROC __glColorMask__;
extern FARPROC __glColorMaterial__;
extern FARPROC __glColorPointer__;
extern FARPROC __glCopyPixels__;
extern FARPROC __glCopyTexImage1D__;
extern FARPROC __glCopyTexImage2D__;
extern FARPROC __glCopyTexSubImage1D__;
extern FARPROC __glCopyTexSubImage2D__;
extern FARPROC __glCullFace__;
extern FARPROC __glDeleteLists__;
extern FARPROC __glDeleteTextures__;
extern FARPROC __glDepthFunc__;
extern FARPROC __glDepthMask__;
extern FARPROC __glDepthRange__;
extern FARPROC __glDisable__;
extern FARPROC __glDisableClientState__;
extern FARPROC __glDrawArrays__;
extern FARPROC __glDrawBuffer__;
extern FARPROC __glDrawElements__;
extern FARPROC __glDrawPixels__;
extern FARPROC __glEdgeFlag__;
extern FARPROC __glEdgeFlagPointer__;
extern FARPROC __glEdgeFlagv__;
extern FARPROC __glEnable__;
extern FARPROC __glEnableClientState__;
extern FARPROC __glEnd__;
extern FARPROC __glEndList__;
extern FARPROC __glEvalCoord1d__;
extern FARPROC __glEvalCoord1dv__;
extern FARPROC __glEvalCoord1f__;
extern FARPROC __glEvalCoord1fv__;
extern FARPROC __glEvalCoord2d__;
extern FARPROC __glEvalCoord2dv__;
extern FARPROC __glEvalCoord2f__;
extern FARPROC __glEvalCoord2fv__;
extern FARPROC __glEvalMesh1__;
extern FARPROC __glEvalMesh2__;
extern FARPROC __glEvalPoint1__;
extern FARPROC __glEvalPoint2__;
extern FARPROC __glFeedbackBuffer__;
extern FARPROC __glFinish__;
extern FARPROC __glFlush__;
extern FARPROC __glFogf__;
extern FARPROC __glFogfv__;
extern FARPROC __glFogi__;
extern FARPROC __glFogiv__;
extern FARPROC __glFrontFace__;
extern FARPROC __glFrustum__;
extern FARPROC __glGenLists__;
extern FARPROC __glGenTextures__;
extern FARPROC __glGetBooleanv__;
extern FARPROC __glGetClipPlane__;
extern FARPROC __glGetDoublev__;
extern FARPROC __glGetError__;
extern FARPROC __glGetFloatv__;
extern FARPROC __glGetIntegerv__;
extern FARPROC __glGetLightfv__;
extern FARPROC __glGetLightiv__;
extern FARPROC __glGetMapdv__;
extern FARPROC __glGetMapfv__;
extern FARPROC __glGetMapiv__;
extern FARPROC __glGetMaterialfv__;
extern FARPROC __glGetMaterialiv__;
extern FARPROC __glGetPixelMapfv__;
extern FARPROC __glGetPixelMapuiv__;
extern FARPROC __glGetPixelMapusv__;
extern FARPROC __glGetPointerv__;
extern FARPROC __glGetPolygonStipple__;
extern FARPROC __glGetString__;
extern FARPROC __glGetTexEnvfv__;
extern FARPROC __glGetTexEnviv__;
extern FARPROC __glGetTexGendv__;
extern FARPROC __glGetTexGenfv__;
extern FARPROC __glGetTexGeniv__;
extern FARPROC __glGetTexImage__;
extern FARPROC __glGetTexLevelParameterfv__;
extern FARPROC __glGetTexLevelParameteriv__;
extern FARPROC __glGetTexParameterfv__;
extern FARPROC __glGetTexParameteriv__;
extern FARPROC __glHint__;
extern FARPROC __glIndexMask__;
extern FARPROC __glIndexPointer__;
extern FARPROC __glIndexd__;
extern FARPROC __glIndexdv__;
extern FARPROC __glIndexf__;
extern FARPROC __glIndexfv__;
extern FARPROC __glIndexi__;
extern FARPROC __glIndexiv__;
extern FARPROC __glIndexs__;
extern FARPROC __glIndexsv__;
extern FARPROC __glIndexub__;
extern FARPROC __glIndexubv__;
extern FARPROC __glInitNames__;
extern FARPROC __glInterleavedArrays__;
extern FARPROC __glIsEnabled__;
extern FARPROC __glIsList__;
extern FARPROC __glIsTexture__;
extern FARPROC __glLightModelf__;
extern FARPROC __glLightModelfv__;
extern FARPROC __glLightModeli__;
extern FARPROC __glLightModeliv__;
extern FARPROC __glLightf__;
extern FARPROC __glLightfv__;
extern FARPROC __glLighti__;
extern FARPROC __glLightiv__;
extern FARPROC __glLineStipple__;
extern FARPROC __glLineWidth__;
extern FARPROC __glListBase__;
extern FARPROC __glLoadIdentity__;
extern FARPROC __glLoadMatrixd__;
extern FARPROC __glLoadMatrixf__;
extern FARPROC __glLoadName__;
extern FARPROC __glLogicOp__;
extern FARPROC __glMap1d__;
extern FARPROC __glMap1f__;
extern FARPROC __glMap2d__;
extern FARPROC __glMap2f__;
extern FARPROC __glMapGrid1d__;
extern FARPROC __glMapGrid1f__;
extern FARPROC __glMapGrid2d__;
extern FARPROC __glMapGrid2f__;
extern FARPROC __glMaterialf__;
extern FARPROC __glMaterialfv__;
extern FARPROC __glMateriali__;
extern FARPROC __glMaterialiv__;
extern FARPROC __glMatrixMode__;
extern FARPROC __glMultMatrixd__;
extern FARPROC __glMultMatrixf__;
extern FARPROC __glNewList__;
extern FARPROC __glNormal3b__;
extern FARPROC __glNormal3bv__;
extern FARPROC __glNormal3d__;
extern FARPROC __glNormal3dv__;
extern FARPROC __glNormal3f__;
extern FARPROC __glNormal3fv__;
extern FARPROC __glNormal3i__;
extern FARPROC __glNormal3iv__;
extern FARPROC __glNormal3s__;
extern FARPROC __glNormal3sv__;
extern FARPROC __glNormalPointer__;
extern FARPROC __glOrtho__;
extern FARPROC __glPassThrough__;
extern FARPROC __glPixelMapfv__;
extern FARPROC __glPixelMapuiv__;
extern FARPROC __glPixelMapusv__;
extern FARPROC __glPixelStoref__;
extern FARPROC __glPixelStorei__;
extern FARPROC __glPixelTransferf__;
extern FARPROC __glPixelTransferi__;
extern FARPROC __glPixelZoom__;
extern FARPROC __glPointSize__;
extern FARPROC __glPolygonMode__;
extern FARPROC __glPolygonOffset__;
extern FARPROC __glPolygonStipple__;
extern FARPROC __glPopAttrib__;
extern FARPROC __glPopClientAttrib__;
extern FARPROC __glPopMatrix__;
extern FARPROC __glPopName__;
extern FARPROC __glPrioritizeTextures__;
extern FARPROC __glPushAttrib__;
extern FARPROC __glPushClientAttrib__;
extern FARPROC __glPushMatrix__;
extern FARPROC __glPushName__;
extern FARPROC __glRasterPos2d__;
extern FARPROC __glRasterPos2dv__;
extern FARPROC __glRasterPos2f__;
extern FARPROC __glRasterPos2fv__;
extern FARPROC __glRasterPos2i__;
extern FARPROC __glRasterPos2iv__;
extern FARPROC __glRasterPos2s__;
extern FARPROC __glRasterPos2sv__;
extern FARPROC __glRasterPos3d__;
extern FARPROC __glRasterPos3dv__;
extern FARPROC __glRasterPos3f__;
extern FARPROC __glRasterPos3fv__;
extern FARPROC __glRasterPos3i__;
extern FARPROC __glRasterPos3iv__;
extern FARPROC __glRasterPos3s__;
extern FARPROC __glRasterPos3sv__;
extern FARPROC __glRasterPos4d__;
extern FARPROC __glRasterPos4dv__;
extern FARPROC __glRasterPos4f__;
extern FARPROC __glRasterPos4fv__;
extern FARPROC __glRasterPos4i__;
extern FARPROC __glRasterPos4iv__;
extern FARPROC __glRasterPos4s__;
extern FARPROC __glRasterPos4sv__;
extern FARPROC __glReadBuffer__;
extern FARPROC __glReadPixels__;
extern FARPROC __glRectd__;
extern FARPROC __glRectdv__;
extern FARPROC __glRectf__;
extern FARPROC __glRectfv__;
extern FARPROC __glRecti__;
extern FARPROC __glRectiv__;
extern FARPROC __glRects__;
extern FARPROC __glRectsv__;
extern FARPROC __glRenderMode__;
extern FARPROC __glRotated__;
extern FARPROC __glRotatef__;
extern FARPROC __glScaled__;
extern FARPROC __glScalef__;
extern FARPROC __glScissor__;
extern FARPROC __glSelectBuffer__;
extern FARPROC __glShadeModel__;
extern FARPROC __glStencilFunc__;
extern FARPROC __glStencilMask__;
extern FARPROC __glStencilOp__;
extern FARPROC __glTexCoord1d__;
extern FARPROC __glTexCoord1dv__;
extern FARPROC __glTexCoord1f__;
extern FARPROC __glTexCoord1fv__;
extern FARPROC __glTexCoord1i__;
extern FARPROC __glTexCoord1iv__;
extern FARPROC __glTexCoord1s__;
extern FARPROC __glTexCoord1sv__;
extern FARPROC __glTexCoord2d__;
extern FARPROC __glTexCoord2dv__;
extern FARPROC __glTexCoord2f__;
extern FARPROC __glTexCoord2fv__;
extern FARPROC __glTexCoord2i__;
extern FARPROC __glTexCoord2iv__;
extern FARPROC __glTexCoord2s__;
extern FARPROC __glTexCoord2sv__;
extern FARPROC __glTexCoord3d__;
extern FARPROC __glTexCoord3dv__;
extern FARPROC __glTexCoord3f__;
extern FARPROC __glTexCoord3fv__;
extern FARPROC __glTexCoord3i__;
extern FARPROC __glTexCoord3iv__;
extern FARPROC __glTexCoord3s__;
extern FARPROC __glTexCoord3sv__;
extern FARPROC __glTexCoord4d__;
extern FARPROC __glTexCoord4dv__;
extern FARPROC __glTexCoord4f__;
extern FARPROC __glTexCoord4fv__;
extern FARPROC __glTexCoord4i__;
extern FARPROC __glTexCoord4iv__;
extern FARPROC __glTexCoord4s__;
extern FARPROC __glTexCoord4sv__;
extern FARPROC __glTexCoordPointer__;
extern FARPROC __glTexEnvf__;
extern FARPROC __glTexEnvfv__;
extern FARPROC __glTexEnvi__;
extern FARPROC __glTexEnviv__;
extern FARPROC __glTexGend__;
extern FARPROC __glTexGendv__;
extern FARPROC __glTexGenf__;
extern FARPROC __glTexGenfv__;
extern FARPROC __glTexGeni__;
extern FARPROC __glTexGeniv__;
extern FARPROC __glTexImage1D__;
extern FARPROC __glTexImage2D__;
extern FARPROC __glTexParameterf__;
extern FARPROC __glTexParameterfv__;
extern FARPROC __glTexParameteri__;
extern FARPROC __glTexParameteriv__;
extern FARPROC __glTexSubImage1D__;
extern FARPROC __glTexSubImage2D__;
extern FARPROC __glTranslated__;
extern FARPROC __glTranslatef__;
extern FARPROC __glVertex2d__;
extern FARPROC __glVertex2dv__;
extern FARPROC __glVertex2f__;
extern FARPROC __glVertex2fv__;
extern FARPROC __glVertex2i__;
extern FARPROC __glVertex2iv__;
extern FARPROC __glVertex2s__;
extern FARPROC __glVertex2sv__;
extern FARPROC __glVertex3d__;
extern FARPROC __glVertex3dv__;
extern FARPROC __glVertex3f__;
extern FARPROC __glVertex3fv__;
extern FARPROC __glVertex3i__;
extern FARPROC __glVertex3iv__;
extern FARPROC __glVertex3s__;
extern FARPROC __glVertex3sv__;
extern FARPROC __glVertex4d__;
extern FARPROC __glVertex4dv__;
extern FARPROC __glVertex4f__;
extern FARPROC __glVertex4fv__;
extern FARPROC __glVertex4i__;
extern FARPROC __glVertex4iv__;
extern FARPROC __glVertex4s__;
extern FARPROC __glVertex4sv__;
extern FARPROC __glVertexPointer__;
extern FARPROC __glViewport__;
extern FARPROC __wglChoosePixelFormat__;
extern FARPROC __wglGetLayerPaletteEntries__;
extern FARPROC __wglCopyContext__;
extern FARPROC __wglDeleteContext__;
extern FARPROC __wglDescribeLayerPlane__;
extern FARPROC __wglGetCurrentDC__;
extern FARPROC __wglCreateContext__;
extern FARPROC __wglCreateLayerContext__;
extern FARPROC __wglGetCurrentContext__;
extern FARPROC __wglGetDefaultProcAddress__;
extern FARPROC __wglUseFontOutlinesW__;
extern FARPROC __wglDescribePixelFormat__;
extern FARPROC __wglGetPixelFormat__;
extern FARPROC __wglGetProcAddress__;
extern FARPROC __wglMakeCurrent__;
extern FARPROC __wglRealizeLayerPalette__;
extern FARPROC __wglSetLayerPaletteEntries__;
extern FARPROC __wglSetPixelFormat__;
extern FARPROC __wglShareLists__;
extern FARPROC __wglSwapBuffers__;
extern FARPROC __wglSwapLayerBuffers__;
extern FARPROC __wglSwapMultipleBuffers__;
extern FARPROC __wglUseFontBitmapsA__;
extern FARPROC __wglUseFontBitmapsW__;
extern FARPROC __wglUseFontOutlinesA__;


void load_functions(HMODULE dll)
{
__glAccum__ = GetProcAddress(dll, "glAccum");
__glAlphaFunc__ = GetProcAddress(dll, "glAlphaFunc");
__glAreTexturesResident__ = GetProcAddress(dll, "glAreTexturesResident");
__glArrayElement__ = GetProcAddress(dll, "glArrayElement");
__glBegin__ = GetProcAddress(dll, "glBegin");
__glBindTexture__ = GetProcAddress(dll, "glBindTexture");
__glBitmap__ = GetProcAddress(dll, "glBitmap");
__glBlendFunc__ = GetProcAddress(dll, "glBlendFunc");
__glCallList__ = GetProcAddress(dll, "glCallList");
__glCallLists__ = GetProcAddress(dll, "glCallLists");
__glClear__ = GetProcAddress(dll, "glClear");
__glClearAccum__ = GetProcAddress(dll, "glClearAccum");
__glClearColor__ = GetProcAddress(dll, "glClearColor");
__glClearDepth__ = GetProcAddress(dll, "glClearDepth");
__glClearIndex__ = GetProcAddress(dll, "glClearIndex");
__glClearStencil__ = GetProcAddress(dll, "glClearStencil");
__glClipPlane__ = GetProcAddress(dll, "glClipPlane");
__glColor3b__ = GetProcAddress(dll, "glColor3b");
__glColor3bv__ = GetProcAddress(dll, "glColor3bv");
__glColor3d__ = GetProcAddress(dll, "glColor3d");
__glColor3dv__ = GetProcAddress(dll, "glColor3dv");
__glColor3f__ = GetProcAddress(dll, "glColor3f");
__glColor3fv__ = GetProcAddress(dll, "glColor3fv");
__glColor3i__ = GetProcAddress(dll, "glColor3i");
__glColor3iv__ = GetProcAddress(dll, "glColor3iv");
__glColor3s__ = GetProcAddress(dll, "glColor3s");
__glColor3sv__ = GetProcAddress(dll, "glColor3sv");
__glColor3ub__ = GetProcAddress(dll, "glColor3ub");
__glColor3ubv__ = GetProcAddress(dll, "glColor3ubv");
__glColor3ui__ = GetProcAddress(dll, "glColor3ui");
__glColor3uiv__ = GetProcAddress(dll, "glColor3uiv");
__glColor3us__ = GetProcAddress(dll, "glColor3us");
__glColor3usv__ = GetProcAddress(dll, "glColor3usv");
__glColor4b__ = GetProcAddress(dll, "glColor4b");
__glColor4bv__ = GetProcAddress(dll, "glColor4bv");
__glColor4d__ = GetProcAddress(dll, "glColor4d");
__glColor4dv__ = GetProcAddress(dll, "glColor4dv");
__glColor4f__ = GetProcAddress(dll, "glColor4f");
__glColor4fv__ = GetProcAddress(dll, "glColor4fv");
__glColor4i__ = GetProcAddress(dll, "glColor4i");
__glColor4iv__ = GetProcAddress(dll, "glColor4iv");
__glColor4s__ = GetProcAddress(dll, "glColor4s");
__glColor4sv__ = GetProcAddress(dll, "glColor4sv");
__glColor4ub__ = GetProcAddress(dll, "glColor4ub");
__glColor4ubv__ = GetProcAddress(dll, "glColor4ubv");
__glColor4ui__ = GetProcAddress(dll, "glColor4ui");
__glColor4uiv__ = GetProcAddress(dll, "glColor4uiv");
__glColor4us__ = GetProcAddress(dll, "glColor4us");
__glColor4usv__ = GetProcAddress(dll, "glColor4usv");
__glColorMask__ = GetProcAddress(dll, "glColorMask");
__glColorMaterial__ = GetProcAddress(dll, "glColorMaterial");
__glColorPointer__ = GetProcAddress(dll, "glColorPointer");
__glCopyPixels__ = GetProcAddress(dll, "glCopyPixels");
__glCopyTexImage1D__ = GetProcAddress(dll, "glCopyTexImage1D");
__glCopyTexImage2D__ = GetProcAddress(dll, "glCopyTexImage2D");
__glCopyTexSubImage1D__ = GetProcAddress(dll, "glCopyTexSubImage1D");
__glCopyTexSubImage2D__ = GetProcAddress(dll, "glCopyTexSubImage2D");
__glCullFace__ = GetProcAddress(dll, "glCullFace");
__glDeleteLists__ = GetProcAddress(dll, "glDeleteLists");
__glDeleteTextures__ = GetProcAddress(dll, "glDeleteTextures");
__glDepthFunc__ = GetProcAddress(dll, "glDepthFunc");
__glDepthMask__ = GetProcAddress(dll, "glDepthMask");
__glDepthRange__ = GetProcAddress(dll, "glDepthRange");
__glDisable__ = GetProcAddress(dll, "glDisable");
__glDisableClientState__ = GetProcAddress(dll, "glDisableClientState");
__glDrawArrays__ = GetProcAddress(dll, "glDrawArrays");
__glDrawBuffer__ = GetProcAddress(dll, "glDrawBuffer");
__glDrawElements__ = GetProcAddress(dll, "glDrawElements");
__glDrawPixels__ = GetProcAddress(dll, "glDrawPixels");
__glEdgeFlag__ = GetProcAddress(dll, "glEdgeFlag");
__glEdgeFlagPointer__ = GetProcAddress(dll, "glEdgeFlagPointer");
__glEdgeFlagv__ = GetProcAddress(dll, "glEdgeFlagv");
__glEnable__ = GetProcAddress(dll, "glEnable");
__glEnableClientState__ = GetProcAddress(dll, "glEnableClientState");
__glEnd__ = GetProcAddress(dll, "glEnd");
__glEndList__ = GetProcAddress(dll, "glEndList");
__glEvalCoord1d__ = GetProcAddress(dll, "glEvalCoord1d");
__glEvalCoord1dv__ = GetProcAddress(dll, "glEvalCoord1dv");
__glEvalCoord1f__ = GetProcAddress(dll, "glEvalCoord1f");
__glEvalCoord1fv__ = GetProcAddress(dll, "glEvalCoord1fv");
__glEvalCoord2d__ = GetProcAddress(dll, "glEvalCoord2d");
__glEvalCoord2dv__ = GetProcAddress(dll, "glEvalCoord2dv");
__glEvalCoord2f__ = GetProcAddress(dll, "glEvalCoord2f");
__glEvalCoord2fv__ = GetProcAddress(dll, "glEvalCoord2fv");
__glEvalMesh1__ = GetProcAddress(dll, "glEvalMesh1");
__glEvalMesh2__ = GetProcAddress(dll, "glEvalMesh2");
__glEvalPoint1__ = GetProcAddress(dll, "glEvalPoint1");
__glEvalPoint2__ = GetProcAddress(dll, "glEvalPoint2");
__glFeedbackBuffer__ = GetProcAddress(dll, "glFeedbackBuffer");
__glFinish__ = GetProcAddress(dll, "glFinish");
__glFlush__ = GetProcAddress(dll, "glFlush");
__glFogf__ = GetProcAddress(dll, "glFogf");
__glFogfv__ = GetProcAddress(dll, "glFogfv");
__glFogi__ = GetProcAddress(dll, "glFogi");
__glFogiv__ = GetProcAddress(dll, "glFogiv");
__glFrontFace__ = GetProcAddress(dll, "glFrontFace");
__glFrustum__ = GetProcAddress(dll, "glFrustum");
__glGenLists__ = GetProcAddress(dll, "glGenLists");
__glGenTextures__ = GetProcAddress(dll, "glGenTextures");
__glGetBooleanv__ = GetProcAddress(dll, "glGetBooleanv");
__glGetClipPlane__ = GetProcAddress(dll, "glGetClipPlane");
__glGetDoublev__ = GetProcAddress(dll, "glGetDoublev");
__glGetError__ = GetProcAddress(dll, "glGetError");
__glGetFloatv__ = GetProcAddress(dll, "glGetFloatv");
__glGetIntegerv__ = GetProcAddress(dll, "glGetIntegerv");
__glGetLightfv__ = GetProcAddress(dll, "glGetLightfv");
__glGetLightiv__ = GetProcAddress(dll, "glGetLightiv");
__glGetMapdv__ = GetProcAddress(dll, "glGetMapdv");
__glGetMapfv__ = GetProcAddress(dll, "glGetMapfv");
__glGetMapiv__ = GetProcAddress(dll, "glGetMapiv");
__glGetMaterialfv__ = GetProcAddress(dll, "glGetMaterialfv");
__glGetMaterialiv__ = GetProcAddress(dll, "glGetMaterialiv");
__glGetPixelMapfv__ = GetProcAddress(dll, "glGetPixelMapfv");
__glGetPixelMapuiv__ = GetProcAddress(dll, "glGetPixelMapuiv");
__glGetPixelMapusv__ = GetProcAddress(dll, "glGetPixelMapusv");
__glGetPointerv__ = GetProcAddress(dll, "glGetPointerv");
__glGetPolygonStipple__ = GetProcAddress(dll, "glGetPolygonStipple");
__glGetString__ = GetProcAddress(dll, "glGetString");
__glGetTexEnvfv__ = GetProcAddress(dll, "glGetTexEnvfv");
__glGetTexEnviv__ = GetProcAddress(dll, "glGetTexEnviv");
__glGetTexGendv__ = GetProcAddress(dll, "glGetTexGendv");
__glGetTexGenfv__ = GetProcAddress(dll, "glGetTexGenfv");
__glGetTexGeniv__ = GetProcAddress(dll, "glGetTexGeniv");
__glGetTexImage__ = GetProcAddress(dll, "glGetTexImage");
__glGetTexLevelParameterfv__ = GetProcAddress(dll, "glGetTexLevelParameterfv");
__glGetTexLevelParameteriv__ = GetProcAddress(dll, "glGetTexLevelParameteriv");
__glGetTexParameterfv__ = GetProcAddress(dll, "glGetTexParameterfv");
__glGetTexParameteriv__ = GetProcAddress(dll, "glGetTexParameteriv");
__glHint__ = GetProcAddress(dll, "glHint");
__glIndexMask__ = GetProcAddress(dll, "glIndexMask");
__glIndexPointer__ = GetProcAddress(dll, "glIndexPointer");
__glIndexd__ = GetProcAddress(dll, "glIndexd");
__glIndexdv__ = GetProcAddress(dll, "glIndexdv");
__glIndexf__ = GetProcAddress(dll, "glIndexf");
__glIndexfv__ = GetProcAddress(dll, "glIndexfv");
__glIndexi__ = GetProcAddress(dll, "glIndexi");
__glIndexiv__ = GetProcAddress(dll, "glIndexiv");
__glIndexs__ = GetProcAddress(dll, "glIndexs");
__glIndexsv__ = GetProcAddress(dll, "glIndexsv");
__glIndexub__ = GetProcAddress(dll, "glIndexub");
__glIndexubv__ = GetProcAddress(dll, "glIndexubv");
__glInitNames__ = GetProcAddress(dll, "glInitNames");
__glInterleavedArrays__ = GetProcAddress(dll, "glInterleavedArrays");
__glIsEnabled__ = GetProcAddress(dll, "glIsEnabled");
__glIsList__ = GetProcAddress(dll, "glIsList");
__glIsTexture__ = GetProcAddress(dll, "glIsTexture");
__glLightModelf__ = GetProcAddress(dll, "glLightModelf");
__glLightModelfv__ = GetProcAddress(dll, "glLightModelfv");
__glLightModeli__ = GetProcAddress(dll, "glLightModeli");
__glLightModeliv__ = GetProcAddress(dll, "glLightModeliv");
__glLightf__ = GetProcAddress(dll, "glLightf");
__glLightfv__ = GetProcAddress(dll, "glLightfv");
__glLighti__ = GetProcAddress(dll, "glLighti");
__glLightiv__ = GetProcAddress(dll, "glLightiv");
__glLineStipple__ = GetProcAddress(dll, "glLineStipple");
__glLineWidth__ = GetProcAddress(dll, "glLineWidth");
__glListBase__ = GetProcAddress(dll, "glListBase");
__glLoadIdentity__ = GetProcAddress(dll, "glLoadIdentity");
__glLoadMatrixd__ = GetProcAddress(dll, "glLoadMatrixd");
__glLoadMatrixf__ = GetProcAddress(dll, "glLoadMatrixf");
__glLoadName__ = GetProcAddress(dll, "glLoadName");
__glLogicOp__ = GetProcAddress(dll, "glLogicOp");
__glMap1d__ = GetProcAddress(dll, "glMap1d");
__glMap1f__ = GetProcAddress(dll, "glMap1f");
__glMap2d__ = GetProcAddress(dll, "glMap2d");
__glMap2f__ = GetProcAddress(dll, "glMap2f");
__glMapGrid1d__ = GetProcAddress(dll, "glMapGrid1d");
__glMapGrid1f__ = GetProcAddress(dll, "glMapGrid1f");
__glMapGrid2d__ = GetProcAddress(dll, "glMapGrid2d");
__glMapGrid2f__ = GetProcAddress(dll, "glMapGrid2f");
__glMaterialf__ = GetProcAddress(dll, "glMaterialf");
__glMaterialfv__ = GetProcAddress(dll, "glMaterialfv");
__glMateriali__ = GetProcAddress(dll, "glMateriali");
__glMaterialiv__ = GetProcAddress(dll, "glMaterialiv");
__glMatrixMode__ = GetProcAddress(dll, "glMatrixMode");
__glMultMatrixd__ = GetProcAddress(dll, "glMultMatrixd");
__glMultMatrixf__ = GetProcAddress(dll, "glMultMatrixf");
__glNewList__ = GetProcAddress(dll, "glNewList");
__glNormal3b__ = GetProcAddress(dll, "glNormal3b");
__glNormal3bv__ = GetProcAddress(dll, "glNormal3bv");
__glNormal3d__ = GetProcAddress(dll, "glNormal3d");
__glNormal3dv__ = GetProcAddress(dll, "glNormal3dv");
__glNormal3f__ = GetProcAddress(dll, "glNormal3f");
__glNormal3fv__ = GetProcAddress(dll, "glNormal3fv");
__glNormal3i__ = GetProcAddress(dll, "glNormal3i");
__glNormal3iv__ = GetProcAddress(dll, "glNormal3iv");
__glNormal3s__ = GetProcAddress(dll, "glNormal3s");
__glNormal3sv__ = GetProcAddress(dll, "glNormal3sv");
__glNormalPointer__ = GetProcAddress(dll, "glNormalPointer");
__glOrtho__ = GetProcAddress(dll, "glOrtho");
__glPassThrough__ = GetProcAddress(dll, "glPassThrough");
__glPixelMapfv__ = GetProcAddress(dll, "glPixelMapfv");
__glPixelMapuiv__ = GetProcAddress(dll, "glPixelMapuiv");
__glPixelMapusv__ = GetProcAddress(dll, "glPixelMapusv");
__glPixelStoref__ = GetProcAddress(dll, "glPixelStoref");
__glPixelStorei__ = GetProcAddress(dll, "glPixelStorei");
__glPixelTransferf__ = GetProcAddress(dll, "glPixelTransferf");
__glPixelTransferi__ = GetProcAddress(dll, "glPixelTransferi");
__glPixelZoom__ = GetProcAddress(dll, "glPixelZoom");
__glPointSize__ = GetProcAddress(dll, "glPointSize");
__glPolygonMode__ = GetProcAddress(dll, "glPolygonMode");
__glPolygonOffset__ = GetProcAddress(dll, "glPolygonOffset");
__glPolygonStipple__ = GetProcAddress(dll, "glPolygonStipple");
__glPopAttrib__ = GetProcAddress(dll, "glPopAttrib");
__glPopClientAttrib__ = GetProcAddress(dll, "glPopClientAttrib");
__glPopMatrix__ = GetProcAddress(dll, "glPopMatrix");
__glPopName__ = GetProcAddress(dll, "glPopName");
__glPrioritizeTextures__ = GetProcAddress(dll, "glPrioritizeTextures");
__glPushAttrib__ = GetProcAddress(dll, "glPushAttrib");
__glPushClientAttrib__ = GetProcAddress(dll, "glPushClientAttrib");
__glPushMatrix__ = GetProcAddress(dll, "glPushMatrix");
__glPushName__ = GetProcAddress(dll, "glPushName");
__glRasterPos2d__ = GetProcAddress(dll, "glRasterPos2d");
__glRasterPos2dv__ = GetProcAddress(dll, "glRasterPos2dv");
__glRasterPos2f__ = GetProcAddress(dll, "glRasterPos2f");
__glRasterPos2fv__ = GetProcAddress(dll, "glRasterPos2fv");
__glRasterPos2i__ = GetProcAddress(dll, "glRasterPos2i");
__glRasterPos2iv__ = GetProcAddress(dll, "glRasterPos2iv");
__glRasterPos2s__ = GetProcAddress(dll, "glRasterPos2s");
__glRasterPos2sv__ = GetProcAddress(dll, "glRasterPos2sv");
__glRasterPos3d__ = GetProcAddress(dll, "glRasterPos3d");
__glRasterPos3dv__ = GetProcAddress(dll, "glRasterPos3dv");
__glRasterPos3f__ = GetProcAddress(dll, "glRasterPos3f");
__glRasterPos3fv__ = GetProcAddress(dll, "glRasterPos3fv");
__glRasterPos3i__ = GetProcAddress(dll, "glRasterPos3i");
__glRasterPos3iv__ = GetProcAddress(dll, "glRasterPos3iv");
__glRasterPos3s__ = GetProcAddress(dll, "glRasterPos3s");
__glRasterPos3sv__ = GetProcAddress(dll, "glRasterPos3sv");
__glRasterPos4d__ = GetProcAddress(dll, "glRasterPos4d");
__glRasterPos4dv__ = GetProcAddress(dll, "glRasterPos4dv");
__glRasterPos4f__ = GetProcAddress(dll, "glRasterPos4f");
__glRasterPos4fv__ = GetProcAddress(dll, "glRasterPos4fv");
__glRasterPos4i__ = GetProcAddress(dll, "glRasterPos4i");
__glRasterPos4iv__ = GetProcAddress(dll, "glRasterPos4iv");
__glRasterPos4s__ = GetProcAddress(dll, "glRasterPos4s");
__glRasterPos4sv__ = GetProcAddress(dll, "glRasterPos4sv");
__glReadBuffer__ = GetProcAddress(dll, "glReadBuffer");
__glReadPixels__ = GetProcAddress(dll, "glReadPixels");
__glRectd__ = GetProcAddress(dll, "glRectd");
__glRectdv__ = GetProcAddress(dll, "glRectdv");
__glRectf__ = GetProcAddress(dll, "glRectf");
__glRectfv__ = GetProcAddress(dll, "glRectfv");
__glRecti__ = GetProcAddress(dll, "glRecti");
__glRectiv__ = GetProcAddress(dll, "glRectiv");
__glRects__ = GetProcAddress(dll, "glRects");
__glRectsv__ = GetProcAddress(dll, "glRectsv");
__glRenderMode__ = GetProcAddress(dll, "glRenderMode");
__glRotated__ = GetProcAddress(dll, "glRotated");
__glRotatef__ = GetProcAddress(dll, "glRotatef");
__glScaled__ = GetProcAddress(dll, "glScaled");
__glScalef__ = GetProcAddress(dll, "glScalef");
__glScissor__ = GetProcAddress(dll, "glScissor");
__glSelectBuffer__ = GetProcAddress(dll, "glSelectBuffer");
__glShadeModel__ = GetProcAddress(dll, "glShadeModel");
__glStencilFunc__ = GetProcAddress(dll, "glStencilFunc");
__glStencilMask__ = GetProcAddress(dll, "glStencilMask");
__glStencilOp__ = GetProcAddress(dll, "glStencilOp");
__glTexCoord1d__ = GetProcAddress(dll, "glTexCoord1d");
__glTexCoord1dv__ = GetProcAddress(dll, "glTexCoord1dv");
__glTexCoord1f__ = GetProcAddress(dll, "glTexCoord1f");
__glTexCoord1fv__ = GetProcAddress(dll, "glTexCoord1fv");
__glTexCoord1i__ = GetProcAddress(dll, "glTexCoord1i");
__glTexCoord1iv__ = GetProcAddress(dll, "glTexCoord1iv");
__glTexCoord1s__ = GetProcAddress(dll, "glTexCoord1s");
__glTexCoord1sv__ = GetProcAddress(dll, "glTexCoord1sv");
__glTexCoord2d__ = GetProcAddress(dll, "glTexCoord2d");
__glTexCoord2dv__ = GetProcAddress(dll, "glTexCoord2dv");
__glTexCoord2f__ = GetProcAddress(dll, "glTexCoord2f");
__glTexCoord2fv__ = GetProcAddress(dll, "glTexCoord2fv");
__glTexCoord2i__ = GetProcAddress(dll, "glTexCoord2i");
__glTexCoord2iv__ = GetProcAddress(dll, "glTexCoord2iv");
__glTexCoord2s__ = GetProcAddress(dll, "glTexCoord2s");
__glTexCoord2sv__ = GetProcAddress(dll, "glTexCoord2sv");
__glTexCoord3d__ = GetProcAddress(dll, "glTexCoord3d");
__glTexCoord3dv__ = GetProcAddress(dll, "glTexCoord3dv");
__glTexCoord3f__ = GetProcAddress(dll, "glTexCoord3f");
__glTexCoord3fv__ = GetProcAddress(dll, "glTexCoord3fv");
__glTexCoord3i__ = GetProcAddress(dll, "glTexCoord3i");
__glTexCoord3iv__ = GetProcAddress(dll, "glTexCoord3iv");
__glTexCoord3s__ = GetProcAddress(dll, "glTexCoord3s");
__glTexCoord3sv__ = GetProcAddress(dll, "glTexCoord3sv");
__glTexCoord4d__ = GetProcAddress(dll, "glTexCoord4d");
__glTexCoord4dv__ = GetProcAddress(dll, "glTexCoord4dv");
__glTexCoord4f__ = GetProcAddress(dll, "glTexCoord4f");
__glTexCoord4fv__ = GetProcAddress(dll, "glTexCoord4fv");
__glTexCoord4i__ = GetProcAddress(dll, "glTexCoord4i");
__glTexCoord4iv__ = GetProcAddress(dll, "glTexCoord4iv");
__glTexCoord4s__ = GetProcAddress(dll, "glTexCoord4s");
__glTexCoord4sv__ = GetProcAddress(dll, "glTexCoord4sv");
__glTexCoordPointer__ = GetProcAddress(dll, "glTexCoordPointer");
__glTexEnvf__ = GetProcAddress(dll, "glTexEnvf");
__glTexEnvfv__ = GetProcAddress(dll, "glTexEnvfv");
__glTexEnvi__ = GetProcAddress(dll, "glTexEnvi");
__glTexEnviv__ = GetProcAddress(dll, "glTexEnviv");
__glTexGend__ = GetProcAddress(dll, "glTexGend");
__glTexGendv__ = GetProcAddress(dll, "glTexGendv");
__glTexGenf__ = GetProcAddress(dll, "glTexGenf");
__glTexGenfv__ = GetProcAddress(dll, "glTexGenfv");
__glTexGeni__ = GetProcAddress(dll, "glTexGeni");
__glTexGeniv__ = GetProcAddress(dll, "glTexGeniv");
__glTexImage1D__ = GetProcAddress(dll, "glTexImage1D");
__glTexImage2D__ = GetProcAddress(dll, "glTexImage2D");
__glTexParameterf__ = GetProcAddress(dll, "glTexParameterf");
__glTexParameterfv__ = GetProcAddress(dll, "glTexParameterfv");
__glTexParameteri__ = GetProcAddress(dll, "glTexParameteri");
__glTexParameteriv__ = GetProcAddress(dll, "glTexParameteriv");
__glTexSubImage1D__ = GetProcAddress(dll, "glTexSubImage1D");
__glTexSubImage2D__ = GetProcAddress(dll, "glTexSubImage2D");
__glTranslated__ = GetProcAddress(dll, "glTranslated");
__glTranslatef__ = GetProcAddress(dll, "glTranslatef");
__glVertex2d__ = GetProcAddress(dll, "glVertex2d");
__glVertex2dv__ = GetProcAddress(dll, "glVertex2dv");
__glVertex2f__ = GetProcAddress(dll, "glVertex2f");
__glVertex2fv__ = GetProcAddress(dll, "glVertex2fv");
__glVertex2i__ = GetProcAddress(dll, "glVertex2i");
__glVertex2iv__ = GetProcAddress(dll, "glVertex2iv");
__glVertex2s__ = GetProcAddress(dll, "glVertex2s");
__glVertex2sv__ = GetProcAddress(dll, "glVertex2sv");
__glVertex3d__ = GetProcAddress(dll, "glVertex3d");
__glVertex3dv__ = GetProcAddress(dll, "glVertex3dv");
__glVertex3f__ = GetProcAddress(dll, "glVertex3f");
__glVertex3fv__ = GetProcAddress(dll, "glVertex3fv");
__glVertex3i__ = GetProcAddress(dll, "glVertex3i");
__glVertex3iv__ = GetProcAddress(dll, "glVertex3iv");
__glVertex3s__ = GetProcAddress(dll, "glVertex3s");
__glVertex3sv__ = GetProcAddress(dll, "glVertex3sv");
__glVertex4d__ = GetProcAddress(dll, "glVertex4d");
__glVertex4dv__ = GetProcAddress(dll, "glVertex4dv");
__glVertex4f__ = GetProcAddress(dll, "glVertex4f");
__glVertex4fv__ = GetProcAddress(dll, "glVertex4fv");
__glVertex4i__ = GetProcAddress(dll, "glVertex4i");
__glVertex4iv__ = GetProcAddress(dll, "glVertex4iv");
__glVertex4s__ = GetProcAddress(dll, "glVertex4s");
__glVertex4sv__ = GetProcAddress(dll, "glVertex4sv");
__glVertexPointer__ = GetProcAddress(dll, "glVertexPointer");
__glViewport__ = GetProcAddress(dll, "glViewport");
__wglChoosePixelFormat__ = GetProcAddress(dll, "wglChoosePixelFormat");
__wglGetLayerPaletteEntries__ = GetProcAddress(dll, "wglGetLayerPaletteEntries");
__wglCopyContext__ = GetProcAddress(dll, "wglCopyContext");
__wglDeleteContext__ = GetProcAddress(dll, "wglDeleteContext");
__wglDescribeLayerPlane__ = GetProcAddress(dll, "wglDescribeLayerPlane");
__wglGetCurrentDC__ = GetProcAddress(dll, "wglGetCurrentDC");
__wglCreateContext__ = GetProcAddress(dll, "wglCreateContext");
__wglCreateLayerContext__ = GetProcAddress(dll, "wglCreateLayerContext");
__wglGetCurrentContext__ = GetProcAddress(dll, "wglGetCurrentContext");
__wglGetDefaultProcAddress__ = GetProcAddress(dll, "wglGetDefaultProcAddress");
__wglUseFontOutlinesW__ = GetProcAddress(dll, "wglUseFontOutlinesW");
__wglDescribePixelFormat__ = GetProcAddress(dll, "wglDescribePixelFormat");
__wglGetPixelFormat__ = GetProcAddress(dll, "wglGetPixelFormat");
__wglGetProcAddress__ = GetProcAddress(dll, "wglGetProcAddress");
__wglMakeCurrent__ = GetProcAddress(dll, "wglMakeCurrent");
__wglRealizeLayerPalette__ = GetProcAddress(dll, "wglRealizeLayerPalette");
__wglSetLayerPaletteEntries__ = GetProcAddress(dll, "wglSetLayerPaletteEntries");
__wglSetPixelFormat__ = GetProcAddress(dll, "wglSetPixelFormat");
__wglShareLists__ = GetProcAddress(dll, "wglShareLists");
__wglSwapBuffers__ = GetProcAddress(dll, "wglSwapBuffers");
__wglSwapLayerBuffers__ = GetProcAddress(dll, "wglSwapLayerBuffers");
__wglSwapMultipleBuffers__ = GetProcAddress(dll, "wglSwapMultipleBuffers");
__wglUseFontBitmapsA__ = GetProcAddress(dll, "wglUseFontBitmapsA");
__wglUseFontBitmapsW__ = GetProcAddress(dll, "wglUseFontBitmapsW");
__wglUseFontOutlinesA__ = GetProcAddress(dll, "wglUseFontOutlinesA");

}
